begin;

create table if not exists public.client_error_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  context text not null check (char_length(context) between 1 and 80),
  error_code text not null default 'unknown' check (char_length(error_code) between 1 and 80),
  message text not null check (char_length(message) between 1 and 500),
  fingerprint text not null check (char_length(fingerprint) between 1 and 120),
  page_path text not null default '/' check (char_length(page_path) between 1 and 200),
  release_stage integer,
  online boolean,
  created_at timestamptz not null default now()
);

create index if not exists client_error_logs_user_created_idx
  on public.client_error_logs(user_id, created_at desc);
create index if not exists client_error_logs_fingerprint_created_idx
  on public.client_error_logs(fingerprint, created_at desc);

alter table public.client_error_logs enable row level security;

-- 앱 클라이언트는 테이블을 직접 읽거나 쓰지 않는다. 아래 RPC만 실행한다.
revoke all on public.client_error_logs from anon, authenticated;

create or replace function public.log_client_error(
  p_context text,
  p_error_code text,
  p_message text,
  p_fingerprint text,
  p_page_path text,
  p_release_stage integer,
  p_online boolean
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
begin
  if v_user is null then return false; end if;

  -- 같은 사용자·오류는 5분에 한 번, 전체는 시간당 60건까지만 저장한다.
  if exists (
    select 1 from public.client_error_logs
    where user_id = v_user
      and fingerprint = left(coalesce(p_fingerprint, 'unknown'), 120)
      and created_at > now() - interval '5 minutes'
  ) then return false; end if;

  if (select count(*) from public.client_error_logs
      where user_id = v_user and created_at > now() - interval '1 hour') >= 60
  then return false; end if;

  insert into public.client_error_logs(
    user_id, context, error_code, message, fingerprint,
    page_path, release_stage, online
  ) values (
    v_user,
    left(coalesce(nullif(trim(p_context), ''), 'unknown'), 80),
    left(coalesce(nullif(trim(p_error_code), ''), 'unknown'), 80),
    left(coalesce(nullif(trim(p_message), ''), '오류가 발생했습니다.'), 500),
    left(coalesce(nullif(trim(p_fingerprint), ''), 'unknown'), 120),
    left(coalesce(nullif(trim(p_page_path), ''), '/'), 200),
    p_release_stage,
    p_online
  );
  return true;
end;
$$;

revoke all on function public.log_client_error(text,text,text,text,text,integer,boolean) from public;
grant execute on function public.log_client_error(text,text,text,text,text,integer,boolean) to authenticated;

create or replace function public.export_my_error_logs()
returns jsonb
language sql
security definer
set search_path = public
stable
as $$
  select coalesce(jsonb_agg(to_jsonb(x) order by x.created_at desc), '[]'::jsonb)
  from (
    select id, user_id, context, error_code, message, fingerprint,
           page_path, release_stage, online, created_at
    from public.client_error_logs
    where user_id = auth.uid()
  ) x;
$$;

revoke all on function public.export_my_error_logs() from public;
grant execute on function public.export_my_error_logs() to authenticated;

commit;
