'use strict';
(function(){
  const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
  const DB=window.LabDB,Storage=window.LabStorage,Drafts=window.LabDrafts,cfg=window.LAB_CONFIG;
  document.documentElement.dataset.stage=String(cfg.RELEASE_STAGE||'');
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const safeUrl=v=>{try{const u=new URL(v,location.href);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return ''}};
  const fmtDate=v=>{if(!v)return '';const d=new Date(`${String(v).slice(0,10)}T00:00:00`);return new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'long',day:'numeric'}).format(d)};
  const fmtShort=v=>{if(!v)return '';const d=new Date(`${String(v).slice(0,10)}T00:00:00`);return `${d.getMonth()+1}.${d.getDate()}`};
  const fmtTime=v=>v?new Intl.DateTimeFormat('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(v)):'';
  const dateKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
  const money=n=>'₩'+Math.round(Number(n)||0).toLocaleString('ko-KR');
  const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
  const state={profile:null,page:'today',labTab:'ideas',squareTab:'discover',settingsTab:'profile',records:[],recordUrls:new Map(),recordEdit:null,newRecordFiles:[],diaryEdit:null,newDiaryFiles:[],diaryDraftTimer:null,bookEdit:null,calendarView:new Date(),selectedDay:new Date(),calendarEvents:[],habits:[],habitChecks:[],goals:[],projects:[],ideas:[],works:[],finance:[],financeView:new Date(),ownPublications:[],publishTarget:null,projectEdit:null,currentPub:null,comments:[],reportTarget:null,draftTimer:null,networkOnline:navigator.onLine,eventEdit:null,habitEdit:null,lightboxUrls:[],lightboxIndex:0};
  state.calendarView.setDate(1);

  function toast(message,action){const host=$('#toastStack');if(!host)return;const el=document.createElement('div');el.className='toast';const text=document.createElement('span');text.textContent=message;el.appendChild(text);if(action){const b=document.createElement('button');b.className='toast-action';b.type='button';b.textContent=action.label||'다시 시도';b.addEventListener('click',async()=>{el.remove();await action.run()});el.appendChild(b)}host.appendChild(el);setTimeout(()=>el.remove(),action?6000:2800)}
  function setBusy(el,on,label){if(!el)return;if(on){el.dataset.original=el.textContent;el.disabled=true;el.classList.add('loading');if(label)el.textContent=label}else{el.disabled=false;el.classList.remove('loading');if(el.dataset.original){el.textContent=el.dataset.original;delete el.dataset.original}}}
  function syncUI(text,ok=true){const el=$('#syncState');if(!el)return;el.querySelector('span').textContent=text;el.querySelector('i').style.background=ok?'#7ca18d':'#b66a63'}
  function openModal(id){const el=$('#'+id);if(el){el.classList.add('show');el.setAttribute('aria-hidden','false')}}
  function closeModal(id){const el=$('#'+id);if(el){el.classList.remove('show');el.setAttribute('aria-hidden','true')}}
  function moveLightbox(delta){if(!state.lightboxUrls.length)return;state.lightboxIndex=(state.lightboxIndex+delta+state.lightboxUrls.length)%state.lightboxUrls.length;$('#lightboxImage').src=state.lightboxUrls[state.lightboxIndex]}
  function sourceLabel(t){return t==='record'?'기록':t==='project'?'프로젝트':'작업물'}
  function statusLabel(s){return s==='paused'?'일시정지':s==='completed'?'완료':'진행 중'}
  function featureStatus(s){return s==='planned'?'검토 후 계획':s==='working'?'개발 중':s==='done'?'반영 완료':s==='declined'?'보류':'제안됨'}
  function updateNetwork(){state.networkOnline=navigator.onLine;syncUI(state.networkOnline?'연결됨':'오프라인',state.networkOnline)}
  window.addEventListener('online',updateNetwork);window.addEventListener('offline',updateNetwork);

  async function withError(fn,context='작업'){try{syncUI('동기화 중…');const v=await fn();syncUI('연결됨');return v}catch(e){console.error(context,e);syncUI('오류',false);const message=e.message||`${context}에 실패했습니다.`;const retryable=/불러오기|확인|조회|내보내기/.test(context);toast(message,retryable?{label:'다시 시도',run:async()=>{try{await withError(fn,context)}catch{}}}:null);throw e}}

  function hasCommunityTerms(){return !!state.profile?.terms_accepted_at}
  function ensureCommunityTerms(){if(hasCommunityTerms())return true;$('#communityTermsCheck').checked=false;$('#communityTermsAccept').disabled=true;openModal('communityTermsModal');return false}
  async function acceptCommunityTerms(){if(!$('#communityTermsCheck').checked)return;const btn=$('#communityTermsAccept');setBusy(btn,true,'저장 중…');try{state.profile=await withError(()=>DB.acceptTerms('2026-09-09'),'약관 동의');fillProfileUI();closeModal('communityTermsModal');toast('광장 이용약관에 동의했습니다.')}finally{setBusy(btn,false)}}

  function authMode(mode){$$('[data-auth-mode]').forEach(b=>b.classList.toggle('active',b.dataset.authMode===mode));$('#signupNameField').classList.toggle('hidden',mode!=='signup');$('#signupPasswordConfirmField').classList.toggle('hidden',mode!=='signup');$('#signupTermsField').classList.toggle('hidden',mode!=='signup');if(mode!=='signup')$('#authTerms').checked=false;$('#authSubmit').textContent=mode==='signup'?'하루 공간 만들기':'로그인';$('#authPassword').autocomplete=mode==='signup'?'new-password':'current-password';$('#authPasswordConfirm').value='';$('#authForm').dataset.mode=mode;$('#authMessage').textContent=''}
  async function submitAuth(e){
    e.preventDefault();if(DB.initError){$('#authMessage').textContent=DB.initError;return}
    const mode=$('#authForm').dataset.mode||'signin',email=$('#authEmail').value.trim(),password=$('#authPassword').value,confirmPassword=$('#authPasswordConfirm').value,name=$('#authName').value.trim(),accepted=$('#authTerms').checked,btn=$('#authSubmit');
    if(!email||!password){$('#authMessage').textContent='이메일과 비밀번호를 입력해 주세요.';return}if(mode==='signup'&&password.length<8){$('#authMessage').textContent='새 비밀번호는 8자 이상 입력해 주세요.';return}if(mode==='signup'&&password!==confirmPassword){$('#authMessage').textContent='비밀번호 확인이 일치하지 않습니다.';return}if(mode==='signup'&&!name){$('#authMessage').textContent='앱에 표시할 이름을 입력해 주세요.';return}if(mode==='signup'&&!accepted){$('#authMessage').textContent='회원가입 전에 이용약관과 개인정보처리방침에 동의해 주세요.';return}
    setBusy(btn,true,mode==='signup'?'하루 공간 만드는 중…':'로그인 중…');
    try{
      if(mode==='signup'){
        const data=await DB.signUp(email,password,name,true);
        if(!data.session){$('#authMessage').textContent='가입 확인 메일을 보냈습니다. 이메일 인증 후 로그인해 주세요.';authMode('signin');return}
      }else await DB.signIn(email,password);
      await enterApp();
    }catch(err){$('#authMessage').textContent=err.message||'로그인에 실패했습니다.'}finally{setBusy(btn,false)}
  }

  function avatarLetter(name){return String(name||'L').trim().slice(0,1).toUpperCase()||'L'}
  function applyTheme(theme){const t=['light','dark'].includes(theme)?theme:'system';document.documentElement.dataset.theme=t;localStorage.setItem(`lab:theme:${DB.user()?.id||'guest'}`,t)}
  function validTimezone(value){try{new Intl.DateTimeFormat('en-US',{timeZone:value}).format();return true}catch{return false}}
  function fillProfileUI(){const p=state.profile,u=DB.user();if(!p||!u)return;$('#sideLabName').textContent=p.lab_name;$('#sideUserName').textContent=p.display_name;$('#sideUserEmail').textContent=u.email||'';$('#sideAvatar').textContent=avatarLetter(p.display_name);$('#settingsName').value=p.display_name||'';$('#settingsLabName').value=p.lab_name||'';$('#settingsSlug').value=p.slug||'';$('#settingsBio').value=p.bio||'';$('#settingsEmail').textContent=u.email||'계정 이메일';$('#publicProfileToggle').classList.toggle('on',!!p.public_profile);$('#publicProfileToggle').disabled=!cfg.PUBLIC_SHARING_ENABLED;$('#publicProfileToggle').setAttribute('aria-disabled',String(!cfg.PUBLIC_SHARING_ENABLED));const savedTheme=localStorage.getItem(`lab:theme:${u.id}`)||'system';$('#settingsTheme').value=savedTheme;$('#settingsTimezone').value=localStorage.getItem(`lab:timezone:${u.id}`)||Intl.DateTimeFormat().resolvedOptions().timeZone||'Asia/Seoul';applyTheme(savedTheme);document.title=`${p.lab_name} · 하루를 담다`}
  function showOnboarding(){
    const p=state.profile,u=DB.user(),name=(p?.display_name&&p.display_name!=='사용자')?p.display_name:String(u?.user_metadata?.display_name||'').trim();
    const safeName=name||'';$('#authShell').classList.add('hidden');$('#appShell').classList.add('hidden');$('#onboardingShell').classList.remove('hidden');
    $('#onboardingName').value=safeName;$('#onboardingLabName').value=(p?.lab_name&&p.lab_name!=='나의 하루')?p.lab_name:(safeName?`${safeName}의 하루`:'');updateOnboardingPreview();
    setTimeout(()=>$('#onboardingName').focus(),0);
  }
  function updateOnboardingPreview(){const name=$('#onboardingName').value.trim(),lab=$('#onboardingLabName').value.trim();$('#onboardingPreviewName').textContent=lab||(name?`${name}의 하루`:'나의 하루')}
  async function submitOnboarding(e){
    e.preventDefault();const name=$('#onboardingName').value.trim(),lab=$('#onboardingLabName').value.trim(),btn=$('#onboardingSubmit');$('#onboardingMessage').textContent='';
    if(!name){$('#onboardingMessage').textContent='이름을 입력해 주세요.';return}if(!lab){$('#onboardingMessage').textContent='공간 이름을 입력해 주세요.';return}
    setBusy(btn,true,'하루 공간 만드는 중…');try{state.profile=await withError(()=>DB.completeOnboarding(name,lab),'하루 공간 만들기');$('#onboardingShell').classList.add('hidden');$('#appShell').classList.remove('hidden');fillProfileUI();await route('today',{silent:true});toast(`${state.profile.lab_name}이 준비됐어요.`)}catch(err){$('#onboardingMessage').textContent=err.message||'연구실을 만들지 못했습니다.'}finally{setBusy(btn,false)}
  }
  async function enterApp(){
    state.profile=await withError(()=>DB.ensureProfile(),'프로필 불러오기');
    $('#authShell').classList.add('hidden');
    if(!state.profile.onboarding_completed_at){showOnboarding()}else{$('#onboardingShell').classList.add('hidden');$('#appShell').classList.remove('hidden');fillProfileUI();route('today',{silent:true})}
    DB.onAuthChange(async session=>{if(!session){$('#appShell').classList.add('hidden');$('#onboardingShell').classList.add('hidden');$('#authShell').classList.remove('hidden')} });
  }

  const pageTitles={today:['오늘','할 일 · 일정 · 습관'],records:['기록','가볍게 이어 쓰는 나의 기록'],calendar:['캘린더','일정 · 할 일 · 반복 습관'],personal:['가계부','수입 · 지출 · 월별 흐름'],lab:['아이디어','간단한 생각 저장'],diary:['일기','날짜별 하루와 기분'],books:['독서록','읽는 책과 감상'],goals:['목표 설정','최종 목표 · 이번 달 목표'],search:['통합 검색','내 기록 한 번에 찾기'],notifications:['알림함','일정과 새로운 소식'],bug:['버그 제보','불편한 점 알리기'],support:['후원','개발 응원하기'],more:['더보기','전체 메뉴'],square:['광장','선택해서 들어가는 커뮤니티'],settings:['설정','프로필 · 데이터 · 계정']};
  async function route(page,opt={}){
    if(!pageTitles[page])page='today';state.page=page;
    $$('[data-page]').forEach(el=>el.classList.toggle('active',el.dataset.page===page));$$('[data-go]').forEach(el=>el.classList.toggle('active',el.dataset.go===page));
    $('#topbarTitle').textContent=pageTitles[page][0];$('#topbarSub').textContent=pageTitles[page][1];if(!opt.silent)window.scrollTo({top:0,behavior:'smooth'});
    try{if(page==='today')await loadToday();else if(page==='records')await loadRecords();else if(page==='calendar')await loadCalendar();else if(page==='personal'){state.labTab='finance';await loadLab()}else if(page==='lab'){state.labTab='ideas';await loadLab()}else if(page==='diary')await loadDiary();else if(page==='books')await loadBooks();else if(page==='goals')await loadGoalsPage();else if(page==='search')await loadGlobalSearch();else if(page==='notifications')await loadNotifications();else if(page==='square')await loadSquare();else if(page==='settings')await loadSettings()}catch{}
  }

  const quotes=['작은 기록이 긴 시간을 설명해 준다.','완벽한 계획보다 오늘의 한 칸이 오래 간다.','배운 것을 남기면 경험이 자산이 된다.','결과보다 과정의 선택을 기록해 두자.','나만의 기준은 반복해서 적을수록 선명해진다.','오늘 한 가지를 끝내면 내일이 가벼워진다.','남에게 보이기 전, 먼저 나에게 쓸모 있는 기록을 만들자.'];
  function todoKey(){return `lab:today-todos:${DB.user()?.id||'guest'}:${DB.today()}`}
  function readTodos(){try{const rows=JSON.parse(localStorage.getItem(todoKey())||'[]');return Array.isArray(rows)?rows:[]}catch{return[]}}
  function writeTodos(rows){localStorage.setItem(todoKey(),JSON.stringify(rows));renderTodos()}
  function renderTodos(){const rows=readTodos(),done=rows.filter(x=>x.done).length;$('#todayTodoCount').textContent=`${done}/${rows.length} 완료`;$('#todayTodos').innerHTML=rows.length?rows.map(x=>`<div class="mini-item todo-item ${x.done?'done':''}"><button class="check ${x.done?'done':''}" data-todo-toggle="${esc(x.id)}" aria-label="할 일 완료">${x.done?'✓':''}</button><div class="body"><strong>${esc(x.title)}</strong><span>${x.done?'완료':'오늘 할 일'}</span></div><button class="todo-delete" data-todo-delete="${esc(x.id)}" aria-label="할 일 삭제">×</button></div>`).join(''):'<div class="empty">오늘 할 일을 적어보세요.</div>'}
  function addTodo(){const input=$('#todayTodoInput'),title=input.value.trim();if(!title)return toast('오늘 할 일을 입력해 주세요.');const rows=readTodos();rows.push({id:crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`,title:title.slice(0,120),done:false});input.value='';writeTodos(rows)}
  async function loadToday(){
    const day=DB.today(),[data,countdowns]=await withError(()=>Promise.all([DB.dashboard(day),DB.listImportantEvents(day,shiftDay(day,365))]),'오늘 불러오기'),p=state.profile;$('#todayDate').textContent=new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'long',day:'numeric',weekday:'long'}).format(new Date());$('#greetingTitle').textContent=`${p.display_name}님의 오늘`;
    const final=data.goals.find(g=>g.kind==='final'),monthly=data.goals.find(g=>g.kind==='monthly');$('#todayFinalGoal').textContent=final?.title||'아직 최종 목표가 없습니다.';$('#todayMonthlyGoal').textContent=monthly?.title||'이번 달 목표를 정해보세요.';
    const seed=Number(day.replaceAll('-',''));$('#dailyQuote').textContent=quotes[seed%quotes.length];$('#quoteDate').textContent=fmtShort(day);
    const checkMap=new Map(data.checks.map(c=>[c.habit_id,c.completed]));$('#todayHabits').innerHTML=data.habits.length?data.habits.map(h=>`<div class="mini-item"><button class="check ${checkMap.get(h.id)?'done':''}" data-habit-toggle="${h.id}" data-day="${day}" aria-label="체크">${checkMap.get(h.id)?'✓':''}</button><div class="body"><strong>${esc(h.name)}</strong><span>${checkMap.get(h.id)?'오늘 완료':'아직 체크하지 않음'}</span></div></div>`).join(''):'<div class="empty">체크리스트가 없습니다. 캘린더에서 추가해 보세요.</div>';
    $('#todayEvents').innerHTML=data.events.length?data.events.map(e=>`<div class="mini-item"><button class="check ${e.done?'done':''}" data-event-toggle="${e.id}" data-done="${e.done}">${e.done?'✓':''}</button><div class="body"><strong>${e.important?'<span class="important-star">★</span> ':''}${esc(e.name)}</strong><span>${fmtShort(e.start_date)}${e.end_date!==e.start_date?` ~ ${fmtShort(e.end_date)}`:''}</span></div>${!e.done?`<button class="link-btn" data-move-event="${e.id}" data-event-start="${e.start_date}" data-event-end="${e.end_date}" data-event-name="${esc(e.name)}" data-event-important="${!!e.important}">내일로</button>`:''}</div>`).join(''):'<div class="empty">오늘 일정이 없습니다.</div>';
    $('#todayCountdowns').innerHTML=countdowns.length?countdowns.slice(0,3).map(e=>{const days=Math.ceil((new Date(`${e.start_date}T12:00:00`)-new Date(`${day}T12:00:00`))/86400000);return `<div class="mini-item countdown-item"><span class="countdown-badge">${days===0?'D-DAY':`D-${days}`}</span><div class="body"><strong>${esc(e.name)}</strong><span>${fmtDate(e.start_date)}</span></div></div>`}).join(''):'<div class="empty">중요 일정에 표시하면 D-Day를 볼 수 있어요.</div>';
    renderTodos();
    const mem=$('#memoryCard');if(data.memory){mem.classList.remove('hidden');$('#memoryTitle').textContent=`1년 전 오늘 · ${data.memory.title||'기록'}`;$('#memoryBody').textContent=(data.memory.body||'').slice(0,100)||`${data.memory.category} 기록`;$('#memoryOpen').dataset.recordId=data.memory.id;$('#memoryOpen').dataset.recordCategory=data.memory.category}else mem.classList.add('hidden');
  }
  async function quickRecord(){const body=$('#quickRecordText').value.trim();if(!body)return toast('짧은 기록을 적어 주세요.');const btn=$('#quickRecordSave');setBusy(btn,true,'저장 중…');try{await withError(()=>DB.createRecord({category:'생각',body,entry_date:DB.today()}),'빠른 기록');$('#quickRecordText').value='';toast('나의 기록에 저장했습니다.')}finally{setBusy(btn,false)}}

  async function recordsForSimplePages(){const records=await withError(()=>DB.listRecords(),'기록 불러오기');state.records=records;return records}
  const diaryDraftKey=()=>`diary:${DB.user()?.id||'guest'}`;
  function diaryDraftPayload(){return{entry_date:$('#diaryDate').value,mood:$('#diaryMood').value,title:$('#diaryTitle').value,body:$('#diaryBody').value,updated_at:Date.now()}}
  function scheduleDiaryDraft(){clearTimeout(state.diaryDraftTimer);$('#diaryDraftState').textContent='임시저장 중…';state.diaryDraftTimer=setTimeout(async()=>{try{await Drafts.set(diaryDraftKey(),diaryDraftPayload());$('#diaryDraftState').textContent='이 기기에 임시저장됨'}catch{$('#diaryDraftState').textContent='임시저장 실패'}},650)}
  async function restoreDiaryDraft(){if(state.diaryEdit)return;try{const d=await Drafts.get(diaryDraftKey());if(d&&!$('#diaryTitle').value&&!$('#diaryBody').value){$('#diaryDate').value=d.entry_date||DB.today();$('#diaryMood').value=d.mood||'';$('#diaryTitle').value=d.title||'';$('#diaryBody').value=d.body||'';if(d.title||d.body)$('#diaryDraftState').textContent='이전 임시저장을 복원했습니다.'}}catch{}}
  function clearDiaryFiles(){state.newDiaryFiles.forEach(x=>x.url&&URL.revokeObjectURL(x.url));state.newDiaryFiles=[];$('#diaryImages').value=''}
  function renderDiaryFiles(){const existing=(state.diaryEdit?.record_media||[]).sort((a,b)=>a.sort_order-b.sort_order);$('#diaryPhotoPreview').innerHTML=existing.map((m,i)=>`<div class="photo-thumb"><img src="${esc(state.recordUrls.get(m.id)||'')}" alt="기존 사진 ${i+1}"><button data-remove-diary-media="${m.id}" aria-label="사진 삭제">×</button></div>`).concat(state.newDiaryFiles.map((x,i)=>`<div class="photo-thumb"><img src="${esc(x.url)}" alt="새 사진 ${i+1}"><button data-remove-new-diary-photo="${i}" aria-label="사진 제외">×</button></div>`)).join('')}
  function previewDiaryFiles(){const chosen=[...($('#diaryImages').files||[])],existing=state.diaryEdit?.record_media?.length||0;if(existing+state.newDiaryFiles.length+chosen.length>6){$('#diaryImages').value='';return toast('일기 사진은 모두 합쳐 최대 6장까지 추가할 수 있어요.')}for(const f of chosen){if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>10*1024*1024){$('#diaryImages').value='';return toast('JPG, PNG, WebP 사진을 장당 10MB 이하로 선택해 주세요.')}}state.newDiaryFiles.push(...chosen.map(file=>({file,url:URL.createObjectURL(file)})));$('#diaryImages').value='';renderDiaryFiles()}
  function resetDiary(clearDraft=true){state.diaryEdit=null;clearDiaryFiles();$('#diaryDate').value=DB.today();$('#diaryMood').value='';$('#diaryTitle').value='';$('#diaryBody').value='';$('#diarySave').textContent='일기 저장';$('#diaryCancel').classList.add('hidden');$('#diaryDraftState').textContent='임시저장 준비';if(clearDraft&&DB.user())Drafts.del(diaryDraftKey()).catch(()=>{});renderDiaryFiles()}
  async function loadDiary(){if(!$('#diaryDate').value)$('#diaryDate').value=DB.today();const rows=(await recordsForSimplePages()).filter(r=>r.category==='일상').sort((a,b)=>String(b.entry_date).localeCompare(String(a.entry_date))||String(b.created_at).localeCompare(String(a.created_at)));await prepareRecordUrls(rows);$('#diaryList').innerHTML=rows.length?rows.map(r=>{const media=(r.record_media||[]).sort((a,b)=>a.sort_order-b.sort_order);return `<article class="record-card"><div class="record-meta">${r.mood?`<span class="mood">${esc(r.mood)}</span>`:''}<span class="chip">${fmtDate(r.entry_date)}</span></div><h3>${esc(r.title||'오늘의 일기')}</h3><p>${esc(r.body||'')}</p>${media.length?`<div class="record-gallery">${media.map(m=>`<button data-lightbox="${esc(state.recordUrls.get(m.id)||'')}"><img src="${esc(state.recordUrls.get(m.id)||'')}" alt="${esc(m.original_name||'일기 사진')}" loading="lazy"></button>`).join('')}</div>`:''}<div class="record-actions"><button class="btn secondary small" data-edit-diary="${r.id}">수정</button><button class="btn ghost small danger" data-delete-simple-record="${r.id}" data-return-page="diary">삭제</button></div></article>`}).join(''):'<div class="empty">아직 작성한 일기가 없습니다.</div>';await restoreDiaryDraft()}
  function startDiaryEdit(id){const r=state.records.find(x=>x.id===id);if(!r)return;state.diaryEdit=r;clearDiaryFiles();$('#diaryDate').value=r.entry_date;$('#diaryMood').value=r.mood||'';$('#diaryTitle').value=r.title||'';$('#diaryBody').value=r.body||'';$('#diarySave').textContent='수정 저장';$('#diaryCancel').classList.remove('hidden');$('#diaryDraftState').textContent='기존 일기 수정 중';renderDiaryFiles();$('#page-diary .simple-form').scrollIntoView({behavior:'smooth'})}
  async function saveDiary(){const body=$('#diaryBody').value.trim(),title=$('#diaryTitle').value.trim(),files=state.newDiaryFiles.map(x=>x.file),existing=state.diaryEdit?.record_media?.length||0;if(!body&&!title&&!files.length&&!existing)return toast('일기 내용이나 사진을 남겨 주세요.');const btn=$('#diarySave'),wasEdit=!!state.diaryEdit;setBusy(btn,true,files.length?'사진 업로드 중…':'저장 중…');let row=null;try{const payload={category:'일상',mood:$('#diaryMood').value,entry_date:$('#diaryDate').value||DB.today(),title,body,tags:['일기']};row=wasEdit?await withError(()=>DB.updateRecord(state.diaryEdit.id,payload),'일기 수정'):await withError(()=>DB.createRecord(payload),'일기 저장');if(files.length)await withError(()=>Storage.uploadRecordImages(row.id,files,existing),'일기 사진 업로드');resetDiary(true);await loadDiary();toast(wasEdit?'일기를 수정했습니다.':'일기를 저장했습니다.')}catch(e){if(row&&!wasEdit)toast('일기는 저장됐지만 사진 업로드를 마치지 못했습니다. 일기에서 다시 수정해 주세요.')}finally{setBusy(btn,false)}}
  async function removeDiaryMedia(id){const r=state.diaryEdit,m=r?.record_media?.find(x=>x.id===id);if(!m||!confirm('이 사진을 일기에서 삭제할까요?'))return;await withError(()=>Storage.removeRecordMedia(m),'일기 사진 삭제');await loadDiary();startDiaryEdit(r.id);toast('사진을 삭제했습니다.')}

  function bookMeta(record,prefix){return (record.tags||[]).find(t=>t.startsWith(`${prefix}:`))?.slice(prefix.length+1)||''}
  async function loadBooks(){const rows=(await recordsForSimplePages()).filter(r=>r.category==='독서');renderBooks(rows)}
  function renderBooks(source=state.records.filter(r=>r.category==='독서')){const q=$('#bookSearch').value.trim().toLowerCase(),rows=source.filter(r=>[r.title,r.body,(r.tags||[]).join(' ')].join(' ').toLowerCase().includes(q)).sort((a,b)=>String(b.entry_date).localeCompare(String(a.entry_date)));$('#bookList').innerHTML=rows.length?rows.map(r=>{const author=bookMeta(r,'저자'),status=bookMeta(r,'상태'),rating=bookMeta(r,'평점');return `<article class="record-card"><div class="record-meta"><span class="chip">${esc(status||'독서')}</span><span class="muted">${esc(author||'저자 미입력')}</span></div><h3>${esc(r.title||'제목 없는 책')}</h3>${rating?`<div class="book-rating">${'★'.repeat(Number(rating))}</div>`:''}<p>${esc(r.body||'감상 없음')}</p><div class="record-actions"><button class="btn secondary small" data-edit-book="${r.id}">수정</button><button class="btn ghost small danger" data-delete-simple-record="${r.id}" data-return-page="books">삭제</button></div></article>`}).join(''):'<div class="empty">조건에 맞는 독서록이 없습니다.</div>'}
  function resetBook(){state.bookEdit=null;$('#bookTitle').value='';$('#bookAuthor').value='';$('#bookNote').value='';$('#bookStatus').value='읽고 싶음';$('#bookRating').value='';$('#bookSave').textContent='독서록 저장';$('#bookCancel').classList.add('hidden')}
  function startBookEdit(id){const r=state.records.find(x=>x.id===id);if(!r)return;state.bookEdit=r;$('#bookTitle').value=r.title||'';$('#bookAuthor').value=bookMeta(r,'저자');$('#bookStatus').value=bookMeta(r,'상태')||'읽고 싶음';$('#bookRating').value=bookMeta(r,'평점');$('#bookNote').value=r.body||'';$('#bookSave').textContent='수정 저장';$('#bookCancel').classList.remove('hidden');$('#page-books .simple-form').scrollIntoView({behavior:'smooth'})}
  async function saveBook(){const title=$('#bookTitle').value.trim(),author=$('#bookAuthor').value.trim(),note=$('#bookNote').value.trim(),status=$('#bookStatus').value,rating=$('#bookRating').value;if(!title)return toast('책 제목을 입력해 주세요.');const btn=$('#bookSave'),wasEdit=!!state.bookEdit,payload={category:'독서',entry_date:state.bookEdit?.entry_date||DB.today(),title,body:note,tags:[`저자:${author||'미입력'}`,`상태:${status}`,...(rating?[`평점:${rating}`]:[])]};setBusy(btn,true,'저장 중…');try{if(wasEdit)await withError(()=>DB.updateRecord(state.bookEdit.id,payload),'독서록 수정');else await withError(()=>DB.createRecord(payload),'독서록 저장');resetBook();await loadBooks();toast(wasEdit?'독서록을 수정했습니다.':'독서록을 저장했습니다.')}finally{setBusy(btn,false)}}

  async function deleteSimpleRecord(id,returnPage){if(!confirm('이 항목과 첨부 파일을 삭제할까요?'))return;const r=state.records.find(x=>x.id===id),paths=(r?.record_media||[]).map(m=>m.storage_path);await withError(()=>DB.deleteRecord(id),'항목 삭제');if(paths.length)await Storage.removePrivatePaths(paths).catch(e=>console.warn('첨부 파일 정리 실패',e));if(returnPage==='diary')await loadDiary();else await loadBooks();toast('삭제했습니다.')}
  async function openRecordPage(id){await route('records');startRecordEdit(id);$('#recordComposer').scrollIntoView({behavior:'smooth'})}

  async function loadGlobalSearch(){const [records,events,ideas,finance]=await withError(()=>Promise.all([DB.listRecords(),DB.listEventsForMonth('2000-01-01','2100-12-31'),DB.listIdeas(),DB.listFinance()]),'통합 검색 준비');state.records=records;state.calendarEvents=events;state.ideas=ideas;state.finance=finance;renderGlobalSearch()}
  function renderGlobalSearch(){const q=$('#globalSearch').value.trim().toLowerCase(),host=$('#globalSearchResults');if(!q){host.innerHTML='<div class="empty">검색어를 입력하면 모든 개인 자료에서 찾아볼 수 있습니다.</div>';return}const rows=[];state.records.filter(x=>[x.title,x.body,(x.tags||[]).join(' ')].join(' ').toLowerCase().includes(q)).forEach(x=>rows.push({type:x.category==='일상'?'일기':x.category==='독서'?'독서록':'기록',title:x.title||'제목 없는 기록',body:x.body||'',page:x.category==='일상'?'diary':x.category==='독서'?'books':'records'}));state.calendarEvents.filter(x=>x.name?.toLowerCase().includes(q)).forEach(x=>rows.push({type:'캘린더',title:x.name,body:`${x.start_date} ~ ${x.end_date}`,page:'calendar'}));state.ideas.filter(x=>[x.title,x.body].join(' ').toLowerCase().includes(q)).forEach(x=>rows.push({type:'아이디어',title:x.title,body:x.body||'',page:'lab'}));state.finance.filter(x=>[x.title,x.category].join(' ').toLowerCase().includes(q)).forEach(x=>rows.push({type:'가계부',title:x.title,body:`${x.category} · ${money(x.amount)}`,page:'personal'}));host.innerHTML=rows.length?rows.slice(0,100).map(x=>`<button class="search-result" data-go="${x.page}"><span class="chip">${esc(x.type)}</span><strong>${esc(x.title)}</strong><small>${esc(x.body.slice(0,120))}</small></button>`).join(''):'<div class="empty">검색 결과가 없습니다.</div>'}

  function notificationKey(){return `lab:notifications-read:${DB.user()?.id||'guest'}`}
  async function loadNotifications(){const data=await withError(()=>DB.dashboard(DB.today()),'알림 불러오기'),read=localStorage.getItem(notificationKey())==='1',items=[];data.events.filter(e=>!e.done).forEach(e=>items.push({title:'오늘 일정',body:e.name}));const undone=readTodos().filter(x=>!x.done);if(undone.length)items.push({title:'남은 할 일',body:`완료하지 않은 할 일이 ${undone.length}개 있습니다.`});$('#notificationList').innerHTML=items.length?items.map(x=>`<article class="notification-item ${read?'read':''}"><span></span><div><strong>${esc(x.title)}</strong><p>${esc(x.body)}</p></div></article>`).join(''):'<div class="empty">새로운 알림이 없습니다.</div>'}
  function readAllNotifications(){localStorage.setItem(notificationKey(),'1');loadNotifications();toast('알림을 모두 읽었습니다.')}

  async function submitBug(){const title=$('#bugTitle').value.trim(),body=$('#bugBody').value.trim(),screen=$('#bugScreen').value;if(!title||!body)return toast('문제 제목과 설명을 입력해 주세요.');const btn=$('#bugSubmit');setBusy(btn,true,'전송 중…');try{await withError(()=>DB.addFeature(`[버그][${screen}] ${title}`,body),'버그 제보');$('#bugTitle').value='';$('#bugBody').value='';toast('버그 제보를 접수했습니다.')}finally{setBusy(btn,false)}}

  function draftPayload(){return{category:'생각',mood:'',entry_date:$('#recordDate').value||DB.today(),title:'',body:$('#recordBody').value,tags:$('#recordTags').value,edit_id:state.recordEdit?.id||null,updated_at:Date.now()}}
  function scheduleDraft(){clearTimeout(state.draftTimer);$('#draftState').textContent='임시저장 중…';state.draftTimer=setTimeout(async()=>{try{await Drafts.set(`record:${DB.user().id}`,draftPayload());$('#draftState').textContent='이 기기에 임시저장됨'}catch{$('#draftState').textContent='임시저장 실패'}},650)}
  async function restoreDraft(){try{const d=await Drafts.get(`record:${DB.user().id}`);if(!d||state.recordEdit||(!d.body&&!d.tags))return;if(!$('#recordBody').value){$('#recordDate').value=d.entry_date||DB.today();$('#recordBody').value=d.body||'';$('#recordTags').value=d.tags||'';$('#draftState').textContent='이전 임시저장을 복원했습니다.'}}catch{}}
  function clearPreviewUrls(){state.newRecordFiles.forEach(x=>{if(x.url)URL.revokeObjectURL(x.url)});state.newRecordFiles=[]}
  function renderNewRecordFiles(){const host=$('#recordPhotoPreview');host.innerHTML=state.newRecordFiles.map((x,i)=>`<div class="photo-thumb"><img src="${esc(x.url)}" alt="새 사진 ${i+1}"><button data-remove-new-photo="${i}" aria-label="사진 제거">×</button></div>`).join('')}
  function previewRecordFiles(){const files=[...$('#recordImages').files];if(state.newRecordFiles.length+files.length>cfg.RECORD_IMAGE_LIMIT){toast(`사진은 최대 ${cfg.RECORD_IMAGE_LIMIT}장까지 선택할 수 있어요.`);$('#recordImages').value='';return}if(files.some(f=>f.size>cfg.MAX_IMAGE_BYTES)){toast('12MB를 넘는 사진이 있습니다.');$('#recordImages').value='';return}state.newRecordFiles=[...state.newRecordFiles,...files.map(file=>({file,url:URL.createObjectURL(file)}))];$('#recordImages').value='';renderNewRecordFiles()}
  function resetRecordComposer(clearDraft=true){state.recordEdit=null;clearPreviewUrls();$('#recordImages').value='';$('#recordDate').value=DB.today();$('#recordBody').value='';$('#recordTags').value='';$('#recordComposerTitle').textContent='새 기록';$('#recordCancelEdit').classList.add('hidden');$('#recordSave').textContent='저장';$('#draftState').textContent='임시저장 준비';if(clearDraft&&DB.user())Drafts.del(`record:${DB.user().id}`).catch(()=>{});renderNewRecordFiles()}
  async function loadRecords(){
    if(!$('#recordDate').value)$('#recordDate').value=DB.today();const records=await withError(()=>DB.listRecords(),'기록 불러오기');state.records=records;state.ownPublications=cfg.COMMUNITY_ENABLED?await DB.listOwnPublications().catch(()=>[]):[];await prepareRecordUrls(records);renderRecords();await restoreDraft();
  }
  async function prepareRecordUrls(records){state.recordUrls.clear();const jobs=[];for(const r of records){for(const m of (r.record_media||[]).slice(0,6)){jobs.push(Storage.signedPrivate(m.storage_path,3600).then(url=>state.recordUrls.set(m.id,url)).catch(()=>state.recordUrls.set(m.id,'')))}}await Promise.all(jobs)}
  function publishedMap(type){return new Map(state.ownPublications.filter(p=>p.source_type===type).map(p=>[p.source_id,p]))}
  function favoriteKey(){return `lab:favorites:${DB.user()?.id||'guest'}`}
  function favoriteIds(){try{return new Set(JSON.parse(localStorage.getItem(favoriteKey())||'[]'))}catch{return new Set()}}
  function toggleFavorite(id){const ids=favoriteIds();ids.has(id)?ids.delete(id):ids.add(id);localStorage.setItem(favoriteKey(),JSON.stringify([...ids]));renderRecords()}
  function renderRecords(){
    const q=$('#recordSearch').value.trim().toLowerCase(),filter=$('#recordFilter').value,sort=$('#recordSort')?.value||'newest',pubs=publishedMap('record'),favs=favoriteIds();let rows=state.records.filter(r=>r.category!=='일상'&&r.category!=='독서').filter(r=>(filter!=='즐겨찾기'||favs.has(r.id))&&(!q||[r.body,(r.tags||[]).join(' ')].join(' ').toLowerCase().includes(q)));rows.sort((a,b)=>sort==='oldest'?String(a.entry_date).localeCompare(String(b.entry_date))||String(a.created_at).localeCompare(String(b.created_at)):String(b.entry_date).localeCompare(String(a.entry_date))||String(b.created_at).localeCompare(String(a.created_at)));
    $('#recordList').innerHTML=rows.length?rows.map(r=>{const media=(r.record_media||[]).sort((a,b)=>a.sort_order-b.sort_order),pub=pubs.get(r.id),fav=favs.has(r.id);return `<article class="record-card"><div class="record-meta"><span class="muted">${fmtDate(r.entry_date)}</span><button class="link-btn ${fav?'on':''}" data-favorite-record="${r.id}" aria-label="즐겨찾기">${fav?'★':'☆'}</button>${pub?`<span class="chip ${pub.audience}">${pub.audience==='public'?'광장 공개':'팔로워 공개'}</span>`:''}</div><p>${esc(r.body||'')}</p>${r.tags?.length?`<div class="row wrap" style="margin-top:10px">${r.tags.map(t=>`<span class="chip">#${esc(t)}</span>`).join('')}</div>`:''}${media.length?`<div class="record-gallery">${media.map(m=>`<button data-lightbox="${esc(state.recordUrls.get(m.id)||'')}"><img src="${esc(state.recordUrls.get(m.id)||'')}" alt="${esc(m.original_name||'기록 사진')}" loading="lazy"></button>`).join('')}</div>`:''}<div class="record-actions"><button class="btn secondary small" data-edit-record="${r.id}">수정</button><button class="btn secondary small" data-publish="record:${r.id}">${pub?'공유 업데이트':'광장 공유'}</button>${pub?`<button class="btn ghost small" data-unpublish="record:${r.id}">공유 취소</button>`:''}<button class="btn ghost small danger" data-delete-record="${r.id}">삭제</button></div></article>`}).join(''):'<div class="empty">조건에 맞는 기록이 없습니다.</div>';
  }
  function startRecordEdit(id){const r=state.records.find(x=>x.id===id);if(!r||r.category==='일상'||r.category==='독서')return;state.recordEdit=r;clearPreviewUrls();$('#recordComposerTitle').textContent='기록 수정';$('#recordCancelEdit').classList.remove('hidden');$('#recordSave').textContent='수정 저장';$('#recordDate').value=r.entry_date;$('#recordBody').value=r.body||'';$('#recordTags').value=(r.tags||[]).join(', ');renderNewRecordFiles();$('#recordComposer').scrollIntoView({behavior:'smooth',block:'start'})}
  async function moveExistingMedia(id,direction){const r=state.recordEdit;if(!r)return;const ordered=[...(r.record_media||[])].sort((a,b)=>a.sort_order-b.sort_order),i=ordered.findIndex(x=>x.id===id),j=direction==='up'?i-1:i+1;if(i<0||j<0||j>=ordered.length)return;[ordered[i],ordered[j]]=[ordered[j],ordered[i]];await withError(()=>DB.reorderRecordMedia(r.id,ordered.map(x=>x.id)),'사진 순서 저장');await loadRecords();startRecordEdit(r.id);toast('사진 순서를 저장했습니다.')}
  async function saveRecord(){
    const payload=draftPayload(),files=state.newRecordFiles.map(x=>x.file),btn=$('#recordSave'),wasEdit=!!state.recordEdit,existingCount=state.recordEdit?.record_media?.length||0;if(!payload.body.trim()&&!files.length&&!existingCount)return toast('내용 또는 사진을 남겨 주세요.');setBusy(btn,true,files.length?'사진 업로드 중…':'저장 중…');
    let row=null;try{row=wasEdit?await withError(()=>DB.updateRecord(state.recordEdit.id,payload),'기록 수정'):await withError(()=>DB.createRecord(payload),'기록 저장');if(files.length)await withError(()=>Storage.uploadRecordImages(row.id,files,existingCount),'사진 업로드');resetRecordComposer(true);await loadRecords();toast(wasEdit?'기록을 수정했습니다.':'기록을 저장했습니다.')}catch(e){if(row&&!wasEdit)toast('글은 저장되었지만 사진 처리 중 문제가 생겼습니다. 기록 목록에서 다시 편집할 수 있어요.')}finally{setBusy(btn,false)}
  }
  async function removeExistingMedia(id){const r=state.recordEdit,m=r?.record_media?.find(x=>x.id===id);if(!m)return;if(!confirm('이 사진을 기록에서 삭제할까요?'))return;await withError(()=>Storage.removeRecordMedia(m),'사진 삭제');await loadRecords();startRecordEdit(r.id);toast('사진을 삭제했습니다.')}
  async function deleteRecord(id){if(!confirm('이 기록과 첨부 사진을 삭제할까요?'))return;const r=state.records.find(x=>x.id===id),paths=(r?.record_media||[]).map(m=>m.storage_path);try{await withError(()=>DB.deleteRecord(id),'기록 삭제');let cleanupFailed=false;if(paths.length)try{await Storage.removePrivatePaths(paths)}catch(e){cleanupFailed=true;console.warn(e)}await loadRecords();toast(cleanupFailed?'기록은 삭제됐고, 일부 파일 정리는 다음 점검에서 다시 확인합니다.':'기록을 삭제했습니다.')}catch{}}

  function monthBounds(view){const start=new Date(view.getFullYear(),view.getMonth(),1),end=new Date(view.getFullYear(),view.getMonth()+1,0);return[dateKey(start),dateKey(end)]}
  function calendarGridBounds(view){const first=new Date(view.getFullYear(),view.getMonth(),1),start=new Date(first);start.setDate(1-first.getDay());const end=new Date(start);end.setDate(start.getDate()+41);return[dateKey(start),dateKey(end)]}
  async function loadCalendar(){const [monthStart,monthEnd]=monthBounds(state.calendarView),[gridStart,gridEnd]=calendarGridBounds(state.calendarView);const [events,habits,checks,records]=await withError(()=>Promise.all([DB.listEventsForMonth(monthStart,monthEnd),DB.listHabits(),DB.checksForRange(gridStart,gridEnd),DB.listRecords()]),'캘린더 불러오기');state.calendarEvents=events;state.habits=habits;state.habitChecks=checks;state.records=records;renderCalendar();renderSelectedDay()}
  function moveCalendar(n){state.calendarView.setMonth(state.calendarView.getMonth()+n);state.calendarView.setDate(1);state.selectedDay=new Date(state.calendarView);loadCalendar().catch(()=>{})}
  function moodClass(value=''){if(value.includes('좋음'))return'good';if(value.includes('평온'))return'calm';if(value.includes('슬픔')||value.includes('아쉬움'))return'sad';if(value.includes('힘듦'))return'hard';return value?'normal':''}
  function renderCalendar(){const v=state.calendarView,first=new Date(v.getFullYear(),v.getMonth(),1),offset=first.getDay(),start=new Date(v.getFullYear(),v.getMonth(),1-offset),today=DB.today(),moods=new Map();state.records.filter(r=>r.category==='일상'&&r.mood).sort((a,b)=>String(a.created_at).localeCompare(String(b.created_at))).forEach(r=>moods.set(r.entry_date,r.mood));$('#calendarMonth').textContent=`${v.getFullYear()}년 ${v.getMonth()+1}월`;let out='';for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const k=dateKey(d),outside=d.getMonth()!==v.getMonth(),events=state.calendarEvents.filter(e=>e.start_date<=k&&e.end_date>=k),range=events.some(e=>e.start_date!==e.end_date),checks=state.habitChecks.filter(c=>c.day===k&&c.completed).length,mood=moods.get(k);const eventHtml=events.slice(0,2).map(e=>{const s=e.start_date===k,t=e.end_date===k;return `<span class="day-event ${e.important?'important':''} ${s?'range-start':''} ${t?'range-end':''} ${!s&&!t?'range-mid':''}"><span>${e.important&&s?'★ ':''}${s||e.start_date===e.end_date?esc(e.name):' '}</span></span>`}).join('');out+=`<button class="day ${outside?'outside':''} ${k===today?'today':''} ${k===dateKey(state.selectedDay)?'selected':''} ${range?'range-day':''}" data-select-day="${k}"><span class="day-number">${d.getDate()}</span>${mood?`<span class="day-mood mood-${moodClass(mood)}" title="${esc(mood)}"></span>`:''}<div class="day-dots">${eventHtml}</div>${checks?'<span class="day-habit-dot"></span>':''}</button>`}$('#calendarDays').innerHTML=out}
  function checksMapFor(day){return new Map(state.habitChecks.filter(c=>c.day===day).map(c=>[c.habit_id,c.completed]))}
  const habitScheduleLabel=s=>s?.type==='weekdays'?'평일':s?.type==='selected_weekdays'?`선택 요일 ${(s.days||[]).map(d=>['일','월','화','수','목','금','토'][d]).join('·')}`:s?.type==='weekly_n'?`주 ${s.count||1}회`:'매일';
  const habitRunsOn=(day,s)=>{if(!s||s.type==='daily'||s.type==='weekly_n')return true;const dow=new Date(`${day}T00:00:00`).getDay();return s.type==='weekdays'?dow>=1&&dow<=5:(s.days||[]).includes(dow)};
  function habitScheduleValue(){const type=$('#habitSchedule').value;if(type==='weekly_n')return{type,count:clamp(Number($('#habitWeeklyCount').value)||1,1,7)};if(type==='selected_weekdays'){const days=$$('#habitWeekdayPicker input:checked').map(x=>Number(x.value));return{type,days:days.length?days:[1]}}return{type}}
  function resetHabitEditor(){state.habitEdit=null;$('#habitNewName').value='';$('#habitSchedule').value='daily';$('#habitWeeklyCount').value='3';$('#habitWeeklyCountWrap').classList.add('hidden');$('#habitWeekdayPicker').classList.add('hidden');$$('#habitWeekdayPicker input').forEach(x=>x.checked=false);$('#habitAdd').textContent='추가';$('#habitCancel').classList.add('hidden')}
  function startHabitEdit(id){const h=state.habits.find(x=>x.id===id);if(!h)return;state.habitEdit=h;$('#habitNewName').value=h.name;$('#habitSchedule').value=h.schedule?.type||'daily';$('#habitWeeklyCount').value=h.schedule?.count||3;$('#habitWeeklyCountWrap').classList.toggle('hidden',$('#habitSchedule').value!=='weekly_n');$('#habitWeekdayPicker').classList.toggle('hidden',$('#habitSchedule').value!=='selected_weekdays');$$('#habitWeekdayPicker input').forEach(x=>x.checked=(h.schedule?.days||[]).includes(Number(x.value)));$('#habitAdd').textContent='수정 저장';$('#habitCancel').classList.remove('hidden');$('#habitNewName').focus()}
  function renderSelectedDay(){const day=dateKey(state.selectedDay),events=state.calendarEvents.filter(e=>e.start_date<=day&&e.end_date>=day),checks=checksMapFor(day);$('#selectedDayTitle').textContent=fmtDate(day);if(!state.eventEdit){$('#eventStart').value=day;$('#eventEnd').value=day}$('#selectedEvents').innerHTML=events.length?events.map(e=>`<div class="event-row"><button class="check ${e.done?'done':''}" data-event-toggle="${e.id}" data-done="${e.done}">${e.done?'✓':''}</button><div class="event-copy"><strong>${e.important?'<span class="important-star">★</span> ':''}${esc(e.name)}</strong><span>${fmtShort(e.start_date)}${e.end_date!==e.start_date?` ~ ${fmtShort(e.end_date)}`:''}</span></div>${!e.done?`<button class="link-btn" data-move-event="${e.id}" data-event-start="${e.start_date}" data-event-end="${e.end_date}" data-event-name="${esc(e.name)}" data-event-important="${!!e.important}">다음 날</button>`:''}<button class="link-btn" data-edit-event="${e.id}">수정</button><button data-delete-event="${e.id}">×</button></div>`).join(''):'<div class="empty">이 날짜에는 일정이 없습니다.</div>';const runnable=state.habits.filter(h=>habitRunsOn(day,h.schedule));$('#selectedHabits').innerHTML=runnable.length?runnable.map(h=>`<div class="mini-item"><button class="check ${checks.get(h.id)?'done':''}" data-habit-toggle="${h.id}" data-day="${day}"><span>${checks.get(h.id)?'✓':''}</span></button><div class="body"><strong>${esc(h.name)}</strong><span>${habitScheduleLabel(h.schedule)}</span></div></div>`).join(''):'<div class="empty">이 날짜에 예정된 체크리스트가 없습니다.</div>';$('#habitTemplateList').innerHTML=state.habits.map(h=>`<div class="row"><div><span style="font-size:11px">${esc(h.name)}</span><small class="muted" style="display:block;font-size:9px">${habitScheduleLabel(h.schedule)}</small></div><span class="spacer"></span><button class="link-btn" data-edit-habit="${h.id}">수정</button><button class="link-btn danger" data-delete-habit="${h.id}">삭제</button></div>`).join('')}
  function shiftDay(day,amount=1){const d=new Date(`${day}T12:00:00`);d.setDate(d.getDate()+amount);return dateKey(d)}
  async function moveEventNext(button){const important=button.dataset.eventImportant==='true';await withError(()=>DB.updateEvent(button.dataset.moveEvent,button.dataset.eventName,shiftDay(button.dataset.eventStart),shiftDay(button.dataset.eventEnd),important),'일정 넘기기');toast('일정을 다음 날로 넘겼습니다.');if(state.page==='today')await loadToday();else await loadCalendar()}
  function renderGoalInputs(){const f=state.goals.find(g=>g.kind==='final'),m=state.goals.find(g=>g.kind==='monthly');$('#finalGoalInput').value=f?.title||'';$('#finalGoalReason').value=f?.note||'';$('#finalGoalDeadline').value=f?.deadline||'';$('#monthlyGoalInput').value=m?.title||'';$('#monthlyGoalAction').value=m?.note||''}
  async function loadGoalsPage(){state.goals=await withError(()=>DB.loadGoals(new Date()),'목표 불러오기');renderGoalInputs()}
  async function addEvent(){const name=$('#eventName').value.trim(),start=$('#eventStart').value,end=$('#eventEnd').value||start,important=$('#eventImportant').checked;if(!name)return toast('일정 내용을 입력해 주세요.');if(!start||!end||end<start)return toast('일정 날짜 범위를 확인해 주세요.');if(state.eventEdit){await withError(()=>DB.updateEvent(state.eventEdit.id,name,start,end,important),'일정 수정');state.eventEdit=null;$('#eventAdd').textContent='일정 추가';$('#eventCancel').classList.add('hidden');toast('일정을 수정했습니다.')}else{await withError(()=>DB.addEvent(name,start,end,important),'일정 추가');toast('일정을 추가했습니다.')}$('#eventName').value='';$('#eventImportant').checked=false;await loadCalendar()}
  function startEventEdit(id){const e=state.calendarEvents.find(x=>x.id===id);if(!e)return;state.eventEdit=e;$('#eventName').value=e.name;$('#eventStart').value=e.start_date;$('#eventEnd').value=e.end_date;$('#eventImportant').checked=!!e.important;$('#eventAdd').textContent='일정 수정';$('#eventCancel').classList.remove('hidden');$('#eventName').focus()}
  function cancelEventEdit(){state.eventEdit=null;$('#eventName').value='';$('#eventImportant').checked=false;$('#eventAdd').textContent='일정 추가';$('#eventCancel').classList.add('hidden');renderSelectedDay()}
  async function toggleEvent(id,done){await withError(()=>DB.toggleEvent(id,!done),'일정 체크');if(state.page==='today')await loadToday();else await loadCalendar()}
  async function toggleHabit(id,day){const current=state.page==='today'?null:checksMapFor(day).get(id);let done=current;if(state.page==='today'){const d=await DB.dashboard(day);done=new Map(d.checks.map(c=>[c.habit_id,c.completed])).get(id)}const habit=state.habits.find(h=>h.id===id);if(!done&&habit?.schedule?.type==='weekly_n'){const d=new Date(`${day}T00:00:00`),monday=new Date(d);monday.setDate(d.getDate()-((d.getDay()+6)%7));const start=dateKey(monday),end=new Date(monday);end.setDate(monday.getDate()+6);const count=state.habitChecks.filter(c=>c.habit_id===id&&c.completed&&c.day>=start&&c.day<=dateKey(end)).length;if(count>=Number(habit.schedule.count||1))return toast(`이번 주에는 이미 ${habit.schedule.count||1}회 완료했습니다.`)}await withError(()=>DB.setHabitCheck(id,day,!done),'체크 저장');if(state.page==='today')await loadToday();else await loadCalendar()}
  async function saveGoals(){await withError(()=>DB.saveGoals($('#finalGoalInput').value.trim(),$('#finalGoalDeadline').value,$('#monthlyGoalInput').value.trim(),new Date(),$('#finalGoalReason').value.trim(),$('#monthlyGoalAction').value.trim()),'목표 저장');await loadGoalsPage();toast('목표를 저장했습니다.')}

  async function loadLab(){const [projects,ideas,works,finance]=await withError(()=>Promise.all([DB.listProjects(),DB.listIdeas(),DB.listWorks(),DB.listFinance()]),'내 공간 불러오기');state.projects=projects;state.ideas=ideas;state.works=works;state.finance=finance;state.ownPublications=cfg.COMMUNITY_ENABLED?await DB.listOwnPublications().catch(()=>[]):[];renderLabTabs();renderProjects();renderIdeas();await renderWorks();renderFinance();renderAllLab()}
  function switchLabTab(tab){state.labTab=tab;renderLabTabs();if(state.page!=='lab')route('lab').catch(()=>{})}
  function renderLabTabs(){$$('#labTabs [data-module]').forEach(b=>b.classList.toggle('active',b.dataset.module===state.labTab));$$('#page-lab .module-pane').forEach(p=>p.classList.toggle('active',p.id===`module-${state.labTab}`));if(state.page==='personal')$('#module-finance')?.classList.add('active')}
  function renderAllLab(){const q=$('#labSearch')?.value.trim();if(!$('#labSearchResults'))return;const p=state.projects.filter(x=>labMatches(x,['title','summary'])).map(x=>`<article class="project-card"><span class="chip">프로젝트</span><h3>${esc(x.title)}</h3><p>${esc(x.summary||'')}</p><button class="btn secondary small" data-open-project="${x.id}">열기</button></article>`);const i=state.ideas.filter(x=>labMatches(x,['title','body','next_step'])).map(x=>`<article class="idea-card"><span class="chip">아이디어</span><h3>${esc(x.title)}</h3><p>${esc(x.body||'')}</p></article>`);const w=state.works.filter(x=>labMatches(x,['title','description','category'])).map(x=>`<article class="work-card"><span class="chip">작업물</span><h3>${esc(x.title)}</h3><p>${esc(x.description||'')}</p></article>`);$('#labSearchResults').innerHTML=p.concat(i,w).join('')||`<div class="empty">${q?'검색 결과가 없습니다.':'프로젝트·아이디어·작업물을 한눈에 볼 수 있습니다.'}</div>`}
  const labMatches=(x,fields)=>{const q=$('#labSearch')?.value.trim().toLowerCase();return !q||fields.some(k=>String(x?.[k]||'').toLowerCase().includes(q))};
  function renderProjects(){const pubs=publishedMap('project'),rows=state.projects.filter(p=>labMatches(p,['title','summary','problem','result','learning']));$('#projectList').innerHTML=rows.length?rows.map(p=>`<article class="project-card"><div class="row"><span class="chip">${statusLabel(p.status)}</span>${pubs.get(p.id)?'<span class="chip public">공유 중</span>':''}<span class="spacer"></span></div><div class="project-kicker">PROJECT</div><h3>${esc(p.title)}</h3><p>${esc(p.summary||'프로젝트 설명을 추가해 보세요.')}</p><div class="record-actions"><button class="btn secondary small" data-open-project="${p.id}">상세 편집</button><button class="btn secondary small" data-publish="project:${p.id}">${pubs.get(p.id)?'공유 업데이트':'광장 공유'}</button>${pubs.get(p.id)?`<button class="btn ghost small" data-unpublish="project:${p.id}">공유 취소</button>`:''}</div></article>`).join(''):'<div class="empty">조건에 맞는 프로젝트가 없습니다.</div>'}
  async function addProject(){const title=$('#projectTitle').value.trim();if(!title)return toast('프로젝트 이름을 입력해 주세요.');await withError(()=>DB.addProject({title,summary:$('#projectSummary').value.trim(),status:$('#projectStatus').value,progress:0}),'프로젝트 만들기');$('#projectTitle').value='';$('#projectSummary').value='';await loadLab();toast('프로젝트를 만들었습니다.')}
  function openProject(id){const p=state.projects.find(x=>x.id===id);if(!p)return;state.projectEdit=p;$('#projectModalTitle').textContent=p.title;$('#pdSummary').value=p.summary||'';$('#pdRole').value=p.role||'';$('#pdPeriod').value=p.period||'';$('#pdType').value=p.project_type||'';$('#pdContribution').value=p.contribution||'';$('#pdProblem').value=p.problem||'';$('#pdProcess').value=p.process||'';$('#pdResult').value=p.result||'';$('#pdLearning').value=p.learning||'';$('#pdSkills').value=(p.skills||[]).join(', ');$('#pdStatus').value=p.status;openModal('projectModal')}
  async function saveProjectDetail(){const p=state.projectEdit;if(!p)return;const btn=$('#projectDetailSave');setBusy(btn,true,'저장 중…');try{await withError(()=>DB.updateProject(p.id,{summary:$('#pdSummary').value.trim(),role:$('#pdRole').value.trim(),period:$('#pdPeriod').value.trim(),project_type:$('#pdType').value.trim(),contribution:$('#pdContribution').value.trim(),problem:$('#pdProblem').value.trim(),process:$('#pdProcess').value.trim(),result:$('#pdResult').value.trim(),learning:$('#pdLearning').value.trim(),skills:$('#pdSkills').value.trim(),status:$('#pdStatus').value}),'프로젝트 저장');await uploadPendingProjectFiles(p);closeModal('projectModal');await loadLab();toast('프로젝트를 저장했습니다.')}finally{setBusy(btn,false)}}
  function renderIdeas(){const rows=state.ideas.filter(i=>labMatches(i,['title','body']));$('#ideaList').innerHTML=rows.length?rows.map(i=>`<article class="idea-card"><div class="row"><span class="chip">아이디어</span><span class="spacer"></span><button class="link-btn danger" data-delete-idea="${i.id}">삭제</button></div><h3>${esc(i.title)}</h3><p>${esc(i.body||'간단한 아이디어')}</p></article>`).join(''):'<div class="empty">저장한 아이디어가 없습니다.</div>'}
  async function addIdea(){const title=$('#ideaTitle').value.trim();if(!title)return toast('아이디어 제목을 입력해 주세요.');await withError(()=>DB.addIdea({title,body:$('#ideaBody').value.trim(),next_step:$('#ideaNext').value.trim()}),'아이디어 저장');$('#ideaTitle').value='';$('#ideaBody').value='';$('#ideaNext').value='';await loadLab();toast('아이디어를 저장했습니다.')}
  async function convertIdea(id){await withError(()=>DB.convertIdea(id),'프로젝트 전환');state.labTab='projects';await loadLab();toast('프로젝트로 전환했습니다.')}
  async function renderWorks(){const pubs=publishedMap('work');const cards=[];for(const w of state.works.filter(x=>labMatches(x,['title','description','category']))){let download='';if(w.file_path){download=`<button class="btn secondary small" data-download-work="${w.id}">파일 다운로드</button>`}cards.push(`<article class="work-card"><div class="row"><span class="chip">${esc(w.category)}</span>${pubs.get(w.id)?'<span class="chip public">공유 중</span>':''}<span class="spacer"></span><button class="link-btn" data-edit-work="${w.id}">수정</button><button class="link-btn danger" data-delete-work="${w.id}">삭제</button></div><h3>${esc(w.title)}</h3><p>${esc(w.description||'설명 없음')}</p><div class="record-actions">${download}${w.link&&safeUrl(w.link)?`<a class="btn secondary small" href="${esc(safeUrl(w.link))}" target="_blank" rel="noopener noreferrer">관련 링크</a>`:''}<button class="btn secondary small" data-publish="work:${w.id}">${pubs.get(w.id)?'공유 업데이트':'광장 공유'}</button>${pubs.get(w.id)?`<button class="btn ghost small" data-unpublish="work:${w.id}">공유 취소</button>`:''}</div></article>`)}$('#workList').innerHTML=cards.length?cards.join(''):'<div class="empty">조건에 맞는 작업물이 없습니다.</div>'}
  async function addWork(){const title=$('#workTitle').value.trim(),file=$('#workFile').files[0];if(!title)return toast('작업물 제목을 입력해 주세요.');if(!file&&!$('#workLink').value.trim())return toast('파일이나 관련 링크 중 하나를 추가해 주세요.');const btn=$('#workAdd');setBusy(btn,true,file?'파일 업로드 중…':'저장 중…');let meta=null;try{if(file)meta=await withError(()=>Storage.uploadWorkFile(file),'작업물 파일 업로드');await withError(()=>DB.addWork({category:$('#workCategory').value,title,description:$('#workDescription').value.trim(),link:$('#workLink').value.trim(),file_path:meta?.path,file_name:file?.name,file_size:meta?.size,file_type:meta?.type}),'작업물 저장');$('#workTitle').value='';$('#workDescription').value='';$('#workLink').value='';$('#workFile').value='';await loadLab();toast('작업물을 저장했습니다.')}catch(e){if(meta?.path)await Storage.removePrivatePaths([meta.path]).catch(()=>{});throw e}finally{setBusy(btn,false)}}
  async function editWork(id){const w=state.works.find(x=>x.id===id);if(!w)return;const title=prompt('작업물 제목',w.title);if(title===null)return;const description=prompt('설명',w.description||'');if(description===null)return;const link=prompt('관련 링크(선택)',w.link||'');if(link===null)return;await withError(()=>DB.updateWork(id,{category:w.category,title,description,link}),'작업물 수정');await loadLab();toast('작업물을 수정했습니다.')}
  async function deleteWork(id){if(!confirm('작업물을 삭제할까요?'))return;const w=state.works.find(x=>x.id===id);await withError(()=>DB.deleteWork(id),'작업물 삭제');let cleanupFailed=false;if(w?.file_path)try{await Storage.removePrivatePaths([w.file_path])}catch(e){cleanupFailed=true;console.warn(e)}await loadLab();toast(cleanupFailed?'작업물은 삭제됐고 파일 정리는 다음 점검에서 다시 확인합니다.':'작업물을 삭제했습니다.')}
  function renderFinance(){const view=state.financeView,mk=`${view.getFullYear()}-${String(view.getMonth()+1).padStart(2,'0')}`,month=state.finance.filter(x=>x.tx_date?.startsWith(mk)),income=month.filter(x=>x.tx_type==='income').reduce((s,x)=>s+Number(x.amount),0),expense=month.filter(x=>x.tx_type==='expense').reduce((s,x)=>s+Number(x.amount),0),balances={};[...state.finance].sort((a,b)=>String(a.tx_date).localeCompare(String(b.tx_date))||String(a.created_at).localeCompare(String(b.created_at))).forEach(x=>{if(x.tx_type==='balance')balances[x.title]=Number(x.amount)||0});const balance=Object.values(balances).reduce((s,v)=>s+v,0);$('#financeMonthLabel').textContent=`${view.getFullYear()}년 ${view.getMonth()+1}월`;$('#financeBalance').textContent=money(balance);$('#financeIncome').textContent=money(income);$('#financeExpense').textContent=money(expense);$('#financeNet').textContent=money(income-expense);const byType=type=>{const totals={};month.filter(x=>x.tx_type===type).forEach(x=>totals[x.category||'기타']=(totals[x.category||'기타']||0)+Number(x.amount));return Object.entries(totals).sort((a,b)=>b[1]-a[1])},categoryBlock=(title,type,total)=>{const rows=byType(type);return `<section><h3>${title}</h3>${rows.length?rows.map(([name,value])=>`<div><span>${esc(name)}</span><strong>${money(value)}</strong><i style="--ratio:${total?Math.max(5,Math.round(value/total*100)):0}%"></i></div>`).join(''):'<p class="muted">내역이 없습니다.</p>'}</section>`};$('#financeCategorySummary').innerHTML=categoryBlock('지출 분류','expense',expense)+categoryBlock('수입 분류','income',income);const rows=month.filter(x=>labMatches(x,['title','category']));$('#transactionList').innerHTML=rows.length?rows.slice(0,80).map(x=>`<div class="transaction"><time>${fmtShort(x.tx_date)}</time><div><strong>${esc(x.title)}</strong><small>${esc(x.category)}</small></div><span class="amount ${x.tx_type}">${x.tx_type==='income'?'+':x.tx_type==='expense'?'-':'='}${money(x.amount)}</span><button class="link-btn" data-edit-finance="${x.id}">수정</button><button data-delete-finance="${x.id}">×</button></div>`).join(''):'<div class="empty" style="margin:10px">선택한 달의 가계부 기록이 없습니다.</div>'}
  function moveFinanceMonth(delta){state.financeView=new Date(state.financeView.getFullYear(),state.financeView.getMonth()+delta,1);renderFinance()}
  async function addFinance(){const type=$('#financeType').value,title=$('#financeTitle').value.trim(),amount=Number($('#financeAmount').value.replace(/[^0-9]/g,'')),date=$('#financeDate').value||DB.today();if(!title)return toast(type==='balance'?'잔액 이름을 입력해 주세요.':'내용을 입력해 주세요.');if(!Number.isFinite(amount)||amount<0||(!amount&&type!=='balance'))return toast('금액을 입력해 주세요.');await withError(()=>DB.addFinance({tx_type:type,title,amount,tx_date:date,category:type==='balance'?'잔액 기록':$('#financeCategory').value}),'가계부 저장');$('#financeTitle').value='';$('#financeAmount').value='';await loadLab();toast('가계부에 저장했습니다.')}
  async function editFinance(id){const x=state.finance.find(v=>v.id===id);if(!x)return;const title=prompt('내용',x.title);if(title===null)return;const amount=prompt('금액',String(x.amount));if(amount===null)return;const date=prompt('날짜 (YYYY-MM-DD)',x.tx_date);if(date===null)return;await withError(()=>DB.updateFinance(id,{tx_type:x.tx_type,title,amount:Number(amount.replace(/[^0-9]/g,'')),tx_date:date,category:x.category}),'가계부 수정');await loadLab();toast('가계부 기록을 수정했습니다.')}

  function publicationPayload(source,type){if(type==='record')return{title:source.title||`${source.category} 기록`,body:source.body||'',meta:{category:source.category,mood:source.mood,tags:source.tags,entry_date:source.entry_date}};if(type==='project')return{title:source.title,body:source.summary||source.result||source.problem||'',meta:{status:source.status,skills:source.skills||[]}};return{title:source.title,body:source.description||'',meta:{category:source.category,link:safeUrl(source.link)||'',file_name:source.file_name||''}}}
  function openPublish(type,id){if(!cfg.PUBLIC_SHARING_ENABLED)return toast('공개 포트폴리오는 이후 단계에서 활성화할 예정입니다.');if(!ensureCommunityTerms())return;state.publishTarget={type,id};$('#publishAudience').value='public';$('#publishMedia').checked=true;openModal('publishModal')}
  async function publishCurrent(){if(!ensureCommunityTerms())return;const t=state.publishTarget;if(!t)return;const btn=$('#publishConfirm');setBusy(btn,true,'공유 준비 중…');let newPublicPath=null,oldPub=null;try{const source=await DB.getSource(t.type,t.id);oldPub=await DB.getPublicationForSource(t.type,t.id);const payload=publicationPayload(source,t.type),shareMedia=$('#publishMedia').checked;if(shareMedia){if(t.type==='record'){const media=(source.record_media||[]).sort((a,b)=>a.sort_order-b.sort_order)[0];if(media)newPublicPath=await Storage.copyPrivateToPublic(media.storage_path,media.original_name,'records')}else if(t.type==='work'&&source.file_path){newPublicPath=await Storage.copyPrivateToPublic(source.file_path,source.file_name||'work-file','works');payload.meta.public_file_path=newPublicPath;payload.meta.public_file_name=source.file_name||'첨부 파일';if((source.file_type||'').startsWith('image/'))payload.cover_path=newPublicPath}}
      if(t.type==='record'&&newPublicPath)payload.cover_path=newPublicPath;
      await DB.upsertPublication({source_type:t.type,source_id:t.id,audience:$('#publishAudience').value,title:payload.title,body:payload.body,meta:payload.meta,cover_path:payload.cover_path||null});if(oldPub?.cover_path&&oldPub.cover_path!==payload.cover_path)await Storage.removePublic(oldPub.cover_path).catch(()=>{});if(oldPub?.meta?.public_file_path&&oldPub.meta.public_file_path!==payload.meta.public_file_path)await Storage.removePublic(oldPub.meta.public_file_path).catch(()=>{});state.profile=await DB.ensureProfile();fillProfileUI();closeModal('publishModal');await refreshCurrent();toast('광장에 공유했습니다. 원본은 개인 연구실에 그대로 남아 있습니다.')}catch(e){if(newPublicPath)await Storage.removePublic(newPublicPath).catch(()=>{})}finally{setBusy(btn,false)}}
  async function unpublish(type,id){if(!confirm('광장 공유를 취소할까요? 개인 연구실 원본은 삭제되지 않습니다.'))return;const pub=await DB.getPublicationForSource(type,id);await withError(()=>DB.unpublish(type,id),'공유 취소');if(pub?.cover_path)await Storage.removePublic(pub.cover_path).catch(()=>{});if(pub?.meta?.public_file_path&&pub.meta.public_file_path!==pub.cover_path)await Storage.removePublic(pub.meta.public_file_path).catch(()=>{});await refreshCurrent();toast('광장에서 내렸습니다.')}
  async function refreshCurrent(){if(state.page==='records')await loadRecords();else if(state.page==='lab')await loadLab();else if(state.page==='square')await loadSquare();else if(state.page==='today')await loadToday()}

  async function loadSquare(){if(!cfg.COMMUNITY_ENABLED){$('#squareTabs').classList.add('hidden');$('#squareFeedback').classList.add('hidden');$('#squareDiscover').classList.remove('hidden');$('#squareFeed').innerHTML='<div class="stage-placeholder"><strong>광장은 이후 단계에서 열립니다.</strong><p>3단계에서는 개인 연구실의 기록·일정·프로젝트·작업물·가계부 연결을 먼저 안정화하고 있어요.</p></div>';return}$('#squareTabs').classList.remove('hidden');if(state.squareTab==='feedback')return loadFeatures();const rows=await withError(()=>DB.feed(state.squareTab),'광장 불러오기');renderFeed(rows)}
  function switchSquare(tab){state.squareTab=tab;$$('#squareTabs [data-square]').forEach(b=>b.classList.toggle('active',b.dataset.square===tab));$('#squareDiscover').classList.toggle('hidden',tab==='feedback');$('#squareFeedback').classList.toggle('hidden',tab!=='feedback');loadSquare().catch(()=>{})}
  function renderFeed(rows){
    if(!rows.length){$('#squareFeed').innerHTML=`<div class="empty" style="grid-column:1/-1">${state.squareTab==='following'?'팔로우한 연구실의 새 공유가 아직 없습니다.':'아직 광장에 공유된 내용이 없습니다.'}</div>`;return}
    $('#squareFeed').innerHTML=rows.map(p=>{const cover=p.cover_path?Storage.publicUrl(p.cover_path):'',own=p.user_id===DB.user().id,profileUrl=`./public.html?slug=${encodeURIComponent(p.slug)}`;return `<article class="pub-card">${cover?`<div class="pub-cover"><img src="${esc(cover)}" alt="공유 대표 이미지" loading="lazy"></div>`:''}<div class="pub-body"><div class="pub-author"><div class="avatar">${esc(avatarLetter(p.display_name))}</div><div><strong><a href="${esc(profileUrl)}">${esc(p.lab_name)}</a></strong><span>${esc(p.display_name)} · ${fmtTime(p.published_at)}</span></div>${!own?`<button class="follow-btn ${p.following_author?'on':''}" data-follow="${p.user_id}" data-on="${p.following_author}">${p.following_author?'팔로잉':'팔로우'}</button>`:''}</div><div class="pub-meta"><span class="chip">${sourceLabel(p.source_type)}</span><span class="chip ${p.audience}">${p.audience==='followers'?'팔로워 공개':'전체 공개'}</span></div><h3>${esc(p.title)}</h3><p>${esc(p.body||'')}</p>${p.meta?.public_file_path?`<div class="record-actions"><a class="btn secondary small" href="${esc(Storage.publicUrl(p.meta.public_file_path))}" target="_blank" rel="noopener noreferrer">${esc(p.meta.public_file_name||'공개 파일')} 열기</a></div>`:''}<div class="pub-actions"><button class="${p.liked_by_me?'on':''}" data-like="${p.id}" data-on="${p.liked_by_me}">♡ <span class="count">${p.like_count}</span></button><button data-comments="${p.id}" data-pub-owner="${p.user_id}">💬 <span class="count">${p.comment_count}</span></button><button data-copy-link="${esc(profileUrl)}">↗ 공유</button>${own?`<button class="danger" data-unpublish="${p.source_type}:${p.source_id}">내리기</button>`:`<button class="moderation-btn" data-report-type="publication" data-report-id="${p.id}" data-report-user="${p.user_id}" data-report-label="${esc(p.lab_name)}의 게시물">신고</button><button class="moderation-btn danger" data-block-user="${p.user_id}" data-block-name="${esc(p.display_name)}">차단</button>`}</div></div></article>`}).join('')
  }
  async function toggleFollow(userId,on){if(!ensureCommunityTerms())return;await withError(()=>DB.toggleFollow(userId,on),'팔로우');await loadSquare()}
  async function toggleLike(pubId,on){if(!ensureCommunityTerms())return;await withError(()=>DB.toggleLike(pubId,on),'좋아요');await loadSquare()}
  async function openComments(pubId){state.currentPub=pubId;state.comments=await withError(()=>DB.comments(pubId),'피드백 불러오기');renderComments();openModal('commentModal')}
  function renderComments(){$('#commentList').innerHTML=state.comments.length?state.comments.map(c=>`<div class="mini-item"><div class="body"><strong>${esc(c.display_name)}</strong><span>${fmtTime(c.created_at)}</span><div style="font-size:11px;margin-top:6px;white-space:pre-wrap">${esc(c.body)}</div></div><div class="comment-moderation">${c.user_id===DB.user().id?`<button class="link-btn danger" data-delete-comment="${c.id}">삭제</button>`:`<button class="link-btn" data-report-type="comment" data-report-id="${c.id}" data-report-user="${c.user_id}" data-report-label="${esc(c.display_name)}님의 댓글">신고</button><button class="link-btn danger" data-block-user="${c.user_id}" data-block-name="${esc(c.display_name)}">차단</button>`}</div></div>`).join(''):'<div class="empty">아직 피드백이 없습니다.</div>'}
  async function submitComment(){if(!ensureCommunityTerms())return;const body=$('#commentInput').value.trim();if(!body||!state.currentPub)return;await withError(()=>DB.addComment(state.currentPub,body),'피드백 등록');$('#commentInput').value='';state.comments=await DB.comments(state.currentPub);renderComments();toast('피드백을 남겼습니다.')}
  async function loadFeatures(){const rows=await withError(()=>DB.features(),'개선 제안 불러오기');$('#featureList').innerHTML=rows.length?rows.map(f=>`<article class="feature-card"><button class="vote-btn ${f.voted_by_me?'on':''}" data-vote="${f.id}" data-on="${f.voted_by_me}"><strong>△</strong><span>${f.vote_count}</span></button><div><h4>${esc(f.title)}</h4><p>${esc(f.body||'')}</p><span class="status-badge ${f.status==='done'?'done':''}">${featureStatus(f.status)}</span><span class="muted" style="font-size:8px;margin-left:6px">${esc(f.display_name)} · ${fmtTime(f.created_at)}</span></div></article>`).join(''):'<div class="empty">첫 개선 제안을 남겨보세요.</div>'}
  async function addFeature(){if(!ensureCommunityTerms())return;const title=$('#featureTitle').value.trim(),body=$('#featureBody').value.trim();if(!title)return toast('제안 제목을 입력해 주세요.');await withError(()=>DB.addFeature(title,body),'개선 제안 등록');$('#featureTitle').value='';$('#featureBody').value='';await loadFeatures();toast('개선 제안을 올렸습니다.')}
  async function submitSecurity(){const title=$('#securityTitle').value.trim(),body=$('#securityBody').value.trim();if(!title||!body)return toast('제목과 설명을 입력해 주세요.');await withError(()=>DB.submitSecurityReport(title,body),'보안 제보');$('#securityTitle').value='';$('#securityBody').value='';closeModal('securityModal');toast('비공개 보안 제보를 전송했습니다.')}

  function openReport(type,id,userId,label='광장 콘텐츠'){state.reportTarget={type,id,userId,label};$('#reportTargetLabel').textContent=`${label}을 신고합니다. 신고 내용은 공개되지 않습니다.`;$('#reportReason').value='spam';$('#reportDetails').value='';$('#reportBlockUser').checked=false;$('#reportBlockRow').classList.toggle('hidden',!userId||userId===DB.user().id);openModal('reportModal')}
  async function submitReport(){const t=state.reportTarget;if(!t)return;const btn=$('#reportSubmit');setBusy(btn,true,'접수 중…');try{await withError(()=>DB.reportContent({target_type:t.type,target_id:t.id,target_user_id:t.userId,reason:$('#reportReason').value,details:$('#reportDetails').value.trim()}),'신고 접수');if($('#reportBlockUser').checked&&t.userId&&t.userId!==DB.user().id)await DB.blockUser(t.userId).catch(()=>{});closeModal('reportModal');state.reportTarget=null;toast('신고가 비공개로 접수되었습니다.');if(state.page==='square')await loadSquare()}finally{setBusy(btn,false)}}
  async function blockUser(userId,name='사용자'){if(!userId||userId===DB.user().id)return;if(!confirm(`${name}님을 차단할까요? 서로의 광장 콘텐츠와 상호작용이 앱에서 숨겨집니다.`))return;await withError(()=>DB.blockUser(userId),'사용자 차단');toast('사용자를 차단했습니다.');if(state.page==='square')await loadSquare();if(state.page==='settings')await loadBlockedUsers()}
  async function loadBlockedUsers(){const host=$('#blockedUsers');if(!host)return;const rows=await DB.blockedUsers().catch(()=>[]);host.innerHTML=rows.length?rows.map(x=>`<div class="blocked-user"><div class="avatar">${esc(avatarLetter(x.display_name))}</div><div class="copy"><strong>${esc(x.lab_name||x.display_name)}</strong><span>${esc(x.display_name||'사용자')}</span></div><button class="btn secondary small" data-unblock-user="${x.id}">차단 해제</button></div>`).join(''):'<div class="empty">차단한 사용자가 없습니다.</div>'}
  async function unblockUser(userId){await withError(()=>DB.unblockUser(userId),'차단 해제');toast('차단을 해제했습니다.');await loadBlockedUsers()}

  async function loadSettings(){state.profile=await withError(()=>DB.ensureProfile(),'프로필 불러오기');fillProfileUI();if(cfg.COMMUNITY_ENABLED)await loadBlockedUsers();else if($('#blockedUsers'))$('#blockedUsers').innerHTML='<div class="empty">광장 기능이 열리면 차단 목록을 사용할 수 있어요.</div>'}
  function switchSettings(tab){state.settingsTab=tab;$$('#settingsMenu [data-settings]').forEach(b=>b.classList.toggle('active',b.dataset.settings===tab));$$('.settings-pane').forEach(p=>p.classList.toggle('active',p.id===`settings-${tab}`))}
  async function saveProfile(){const btn=$('#profileSave'),tz=$('#settingsTimezone').value.trim(),theme=$('#settingsTheme').value;if(!validTimezone(tz))return toast('올바른 IANA 시간대를 입력해 주세요. 예: Asia/Seoul');setBusy(btn,true,'저장 중…');try{state.profile=await withError(()=>DB.updateProfile({display_name:$('#settingsName').value,lab_name:$('#settingsLabName').value,slug:$('#settingsSlug').value,bio:$('#settingsBio').value}),'프로필 저장');localStorage.setItem(`lab:timezone:${DB.user().id}`,tz);localStorage.setItem(`lab:theme:${DB.user().id}`,theme);applyTheme(theme);fillProfileUI();toast('프로필과 화면 설정을 저장했습니다.')}finally{setBusy(btn,false)}}
  async function togglePublicProfile(){if(!cfg.PUBLIC_SHARING_ENABLED)return toast('공개 포트폴리오는 이후 단계에서 활성화할 예정입니다.');const next=!state.profile.public_profile;if(!next){const pubs=await DB.listOwnPublications();if(pubs.length)return toast('공개 프로필을 끄려면 먼저 공유 중인 항목을 광장에서 내려주세요.')}state.profile=await withError(()=>DB.updateProfile({public_profile:next}),'공개 프로필 설정');fillProfileUI();toast(next?'공개 연구실 프로필을 켰습니다.':'공개 연구실 프로필을 껐습니다.')}
  async function exportData(){const btn=$('#exportData');setBusy(btn,true,'준비 중…');try{const data=await withError(()=>DB.exportData(),'데이터 내보내기'),blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`personal-lab-export-${DB.today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('내 데이터를 JSON으로 내보냈습니다.')}finally{setBusy(btn,false)}}
  
  async function doLogout(){await DB.signOut();location.reload()}
  async function deleteAccount(){const btn=$('#deleteAccountConfirm');setBusy(btn,true,'삭제 중…');try{await withError(()=>DB.deleteAccount(),'계정 삭제');await DB.signOut().catch(()=>{});location.replace('./delete-account.html?deleted=1')}finally{setBusy(btn,false)}}

  function quick(type){closeModal('quickModal');if(type==='record'){route('records').then(()=>$('#recordBody').focus())}else if(type==='event'){route('calendar').then(()=>$('#eventName').focus())}else if(type==='idea'){state.labTab='ideas';route('lab').then(()=>{$('#module-ideas .module-add').open=true;$('#ideaTitle').focus()})}else if(type==='project'){state.labTab='projects';route('lab').then(()=>{$('#module-projects .module-add').open=true;$('#projectTitle').focus()})}else if(type==='finance'){state.labTab='finance';route('personal').then(()=>{$('#module-finance .module-add').open=true;$('#financeTitle').focus()})}}

  document.addEventListener('click',async e=>{
    const go=e.target.closest('[data-go]');if(go){e.preventDefault();if(go.dataset.labTab)state.labTab=go.dataset.labTab;route(go.dataset.go).catch(()=>{});return}
    const close=e.target.closest('[data-close-modal]');if(close){closeModal(close.dataset.closeModal);return}
    if(e.target.classList.contains('modal-backdrop')){closeModal(e.target.id);return}
    const quickBtn=e.target.closest('[data-quick]');if(quickBtn){quick(quickBtn.dataset.quick);return}
    const todoToggle=e.target.closest('[data-todo-toggle]');if(todoToggle){writeTodos(readTodos().map(x=>x.id===todoToggle.dataset.todoToggle?{...x,done:!x.done}:x));return}
    const todoDelete=e.target.closest('[data-todo-delete]');if(todoDelete){writeTodos(readTodos().filter(x=>x.id!==todoDelete.dataset.todoDelete));return}
    const openRecordBtn=e.target.closest('[data-open-record-page]');if(openRecordBtn){await openRecordPage(openRecordBtn.dataset.openRecordPage);return}
    const editDiary=e.target.closest('[data-edit-diary]');if(editDiary){startDiaryEdit(editDiary.dataset.editDiary);return}
    const editBook=e.target.closest('[data-edit-book]');if(editBook){startBookEdit(editBook.dataset.editBook);return}
    const delSimple=e.target.closest('[data-delete-simple-record]');if(delSimple){await deleteSimpleRecord(delSimple.dataset.deleteSimpleRecord,delSimple.dataset.returnPage);return}
    const rmDiaryNew=e.target.closest('[data-remove-new-diary-photo]');if(rmDiaryNew){const i=Number(rmDiaryNew.dataset.removeNewDiaryPhoto),item=state.newDiaryFiles[i];if(item?.url)URL.revokeObjectURL(item.url);state.newDiaryFiles.splice(i,1);renderDiaryFiles();return}
    const rmDiaryMedia=e.target.closest('[data-remove-diary-media]');if(rmDiaryMedia){await removeDiaryMedia(rmDiaryMedia.dataset.removeDiaryMedia);return}
    const support=e.target.closest('[data-support-amount]');if(support){$$('[data-support-amount]').forEach(b=>b.classList.toggle('selected',b===support));const btn=$('#supportContinue');btn.disabled=false;btn.textContent=`${money(Number(support.dataset.supportAmount))} 후원 준비`;btn.dataset.amount=support.dataset.supportAmount;return}
    const day=e.target.closest('[data-select-day]');if(day){state.selectedDay=new Date(`${day.dataset.selectDay}T00:00:00`);renderCalendar();renderSelectedDay();return}
    const habit=e.target.closest('[data-habit-toggle]');if(habit){await toggleHabit(habit.dataset.habitToggle,habit.dataset.day);return}
    const ev=e.target.closest('[data-event-toggle]');if(ev){await toggleEvent(ev.dataset.eventToggle,ev.dataset.done==='true');return}
    const editEvent=e.target.closest('[data-edit-event]');if(editEvent){startEventEdit(editEvent.dataset.editEvent);return}
    const editHabit=e.target.closest('[data-edit-habit]');if(editHabit){startHabitEdit(editHabit.dataset.editHabit);return}
    const delEvent=e.target.closest('[data-delete-event]');if(delEvent){await withError(()=>DB.deleteEvent(delEvent.dataset.deleteEvent),'일정 삭제');await loadCalendar();return}
    const moveEvent=e.target.closest('[data-move-event]');if(moveEvent){await moveEventNext(moveEvent);return}
    const delHabit=e.target.closest('[data-delete-habit]');if(delHabit){await withError(()=>DB.deleteHabit(delHabit.dataset.deleteHabit),'체크리스트 삭제');await loadCalendar();return}
    const editRecord=e.target.closest('[data-edit-record]');if(editRecord){startRecordEdit(editRecord.dataset.editRecord);return}
    const favRecord=e.target.closest('[data-favorite-record]');if(favRecord){toggleFavorite(favRecord.dataset.favoriteRecord);return}
    const delRecord=e.target.closest('[data-delete-record]');if(delRecord){await deleteRecord(delRecord.dataset.deleteRecord);return}
    const rmNew=e.target.closest('[data-remove-new-photo]');if(rmNew){const i=Number(rmNew.dataset.removeNewPhoto),item=state.newRecordFiles[i];if(item?.url)URL.revokeObjectURL(item.url);state.newRecordFiles.splice(i,1);renderNewRecordFiles();return}
    const rmExisting=e.target.closest('[data-remove-existing-photo]');if(rmExisting){await removeExistingMedia(rmExisting.dataset.removeExistingPhoto);return}
    const moveMedia=e.target.closest('[data-move-media]');if(moveMedia){await moveExistingMedia(moveMedia.dataset.moveMedia,moveMedia.dataset.direction);return}
    const light=e.target.closest('[data-lightbox]');if(light&&light.dataset.lightbox){const gallery=[...light.closest('.record-gallery').querySelectorAll('[data-lightbox]')].map(x=>x.dataset.lightbox).filter(Boolean);state.lightboxUrls=gallery;state.lightboxIndex=Math.max(0,gallery.indexOf(light.dataset.lightbox));$('#lightboxImage').src=state.lightboxUrls[state.lightboxIndex];$('#lightbox').classList.add('show');return}
    const openProj=e.target.closest('[data-open-project]');if(openProj){if(state.page!=='lab'){state.labTab='projects';await route('lab')}openProject(openProj.dataset.openProject);return}
    const delIdea=e.target.closest('[data-delete-idea]');if(delIdea){if(confirm('아이디어를 삭제할까요?')){await DB.deleteIdea(delIdea.dataset.deleteIdea);await loadLab()}return}
    const conv=e.target.closest('[data-convert-idea]');if(conv){await convertIdea(conv.dataset.convertIdea);return}
    const dl=e.target.closest('[data-download-work]');if(dl){const w=state.works.find(x=>x.id===dl.dataset.downloadWork);if(w?.file_path)await Storage.downloadPrivate(w.file_path,w.file_name||'download').catch(err=>toast(err.message));return}
    const editWorkBtn=e.target.closest('[data-edit-work]');if(editWorkBtn){await editWork(editWorkBtn.dataset.editWork);return}
    const delWork=e.target.closest('[data-delete-work]');if(delWork){await deleteWork(delWork.dataset.deleteWork);return}
    const delFin=e.target.closest('[data-delete-finance]');if(delFin){await DB.deleteFinance(delFin.dataset.deleteFinance);await loadLab();return}
    const editFin=e.target.closest('[data-edit-finance]');if(editFin){await editFinance(editFin.dataset.editFinance);return}
    const pub=e.target.closest('[data-publish]');if(pub){const [type,id]=pub.dataset.publish.split(':');openPublish(type,id);return}
    const unpub=e.target.closest('[data-unpublish]');if(unpub){const [type,id]=unpub.dataset.unpublish.split(':');await unpublish(type,id);return}
    const follow=e.target.closest('[data-follow]');if(follow){await toggleFollow(follow.dataset.follow,follow.dataset.on==='true');return}
    const like=e.target.closest('[data-like]');if(like){await toggleLike(like.dataset.like,like.dataset.on==='true');return}
    const comments=e.target.closest('[data-comments]');if(comments){await openComments(comments.dataset.comments);return}
    const delComment=e.target.closest('[data-delete-comment]');if(delComment){await DB.deleteComment(delComment.dataset.deleteComment);state.comments=await DB.comments(state.currentPub);renderComments();return}
    const report=e.target.closest('[data-report-type]');if(report){openReport(report.dataset.reportType,report.dataset.reportId||null,report.dataset.reportUser||null,report.dataset.reportLabel||'광장 콘텐츠');return}
    const block=e.target.closest('[data-block-user]');if(block){await blockUser(block.dataset.blockUser,block.dataset.blockName||'사용자');return}
    const unblock=e.target.closest('[data-unblock-user]');if(unblock){await unblockUser(unblock.dataset.unblockUser);return}
    const vote=e.target.closest('[data-vote]');if(vote){if(!ensureCommunityTerms())return;await DB.toggleFeatureVote(vote.dataset.vote,vote.dataset.on==='true');await loadFeatures();return}
    const copy=e.target.closest('[data-copy-link]');if(copy){const url=new URL(copy.dataset.copyLink,location.href).href;try{await navigator.clipboard.writeText(url);toast('공개 연구실 링크를 복사했습니다.')}catch{toast(url)}return}
  });

  function bind(){
    $$('[data-auth-mode]').forEach(b=>b.addEventListener('click',()=>authMode(b.dataset.authMode)));$('#authForm').addEventListener('submit',submitAuth);$('#onboardingForm').addEventListener('submit',submitOnboarding);$('#onboardingName').addEventListener('input',()=>{if(!$('#onboardingLabName').dataset.custom){$('#onboardingLabName').value=$('#onboardingName').value.trim()?`${$('#onboardingName').value.trim()}의 하루`:''}updateOnboardingPreview()});$('#onboardingLabName').addEventListener('input',()=>{$('#onboardingLabName').dataset.custom='1';updateOnboardingPreview()});$('#onboardingLogout').addEventListener('click',doLogout);authMode('signin');
    $('#quickMain')?.addEventListener('click',()=>openModal('quickModal'));$('#quickRecordSave').addEventListener('click',quickRecord);$('#memoryOpen').addEventListener('click',async e=>{const id=e.target.dataset.recordId,category=e.target.dataset.recordCategory;if(category==='일상'){await route('diary');startDiaryEdit(id)}else if(category==='독서'){await route('books');startBookEdit(id)}else{await route('records');startRecordEdit(id)}});$('#todayTodoAdd').addEventListener('click',addTodo);$('#todayTodoInput').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();addTodo()}});$('#diaryDate').value=DB.today();$('#diarySave').addEventListener('click',saveDiary);$('#diaryCancel').addEventListener('click',()=>resetDiary(true));$('#diaryImages').addEventListener('change',previewDiaryFiles);['#diaryDate','#diaryMood','#diaryTitle','#diaryBody'].forEach(sel=>$(sel).addEventListener('input',scheduleDiaryDraft));$('#bookSave').addEventListener('click',saveBook);$('#bookCancel').addEventListener('click',resetBook);$('#bookSearch').addEventListener('input',()=>renderBooks());$('#globalSearch').addEventListener('input',renderGlobalSearch);$('#notificationReadAll').addEventListener('click',readAllNotifications);$('#bugSubmit').addEventListener('click',submitBug);$('#supportContinue').addEventListener('click',()=>toast('후원 결제는 Google Play 출시 준비 후 연결할 예정입니다.'));
    ['#recordDate','#recordBody','#recordTags'].forEach(sel=>$(sel).addEventListener('input',scheduleDraft));$('#recordImages').addEventListener('change',previewRecordFiles);$('#recordSave').addEventListener('click',saveRecord);$('#recordCancelEdit').addEventListener('click',()=>resetRecordComposer(true));$('#recordNewBtn').addEventListener('click',()=>{resetRecordComposer(false);$('#recordComposer').scrollIntoView({behavior:'smooth'})});$('#recordSearch').addEventListener('input',renderRecords);$('#recordFilter').addEventListener('change',renderRecords);$('#recordSort').addEventListener('change',renderRecords);
    $('#calPrev').addEventListener('click',()=>moveCalendar(-1));$('#calPrevMobile').addEventListener('click',()=>moveCalendar(-1));$('#calNext').addEventListener('click',()=>moveCalendar(1));$('#calNextMobile').addEventListener('click',()=>moveCalendar(1));$('#calToday').addEventListener('click',()=>{state.calendarView=new Date();state.calendarView.setDate(1);state.selectedDay=new Date();loadCalendar()});$('#eventAdd').addEventListener('click',addEvent);$('#eventCancel').addEventListener('click',cancelEventEdit);$('#habitSchedule').addEventListener('change',()=>$('#habitWeeklyCountWrap').classList.toggle('hidden',$('#habitSchedule').value!=='weekly_n'));$('#habitCancel').addEventListener('click',()=>{resetHabitEditor();renderSelectedDay()});$('#habitAdd').addEventListener('click',async()=>{const name=$('#habitNewName').value.trim();if(!name)return toast('체크리스트 이름을 입력해 주세요.');const schedule=habitScheduleValue();if(state.habitEdit){await withError(()=>DB.updateHabit(state.habitEdit.id,name,schedule),'체크리스트 수정');toast('체크리스트를 수정했습니다.')}else{await withError(()=>DB.addHabit(name,schedule),'체크리스트 추가');toast('체크리스트를 추가했습니다.')}resetHabitEditor();await loadCalendar()});$('#goalSave').addEventListener('click',saveGoals);
    $$('#labTabs [data-module]').forEach(b=>b.addEventListener('click',()=>switchLabTab(b.dataset.module)));$('#projectAdd').addEventListener('click',addProject);$('#projectDetailSave').addEventListener('click',saveProjectDetail);$('#projectPublish').addEventListener('click',()=>{if(state.projectEdit){if(!cfg.PUBLIC_SHARING_ENABLED)return toast('공개 포트폴리오는 이후 단계에서 활성화할 예정입니다.');closeModal('projectModal');openPublish('project',state.projectEdit.id)}});$('#projectDelete').addEventListener('click',async()=>{if(state.projectEdit&&confirm('프로젝트를 삭제할까요?')){await DB.deleteProject(state.projectEdit.id);closeModal('projectModal');await loadLab()}});$('#ideaAdd').addEventListener('click',addIdea);$('#workAdd').addEventListener('click',addWork);$('#financeAdd').addEventListener('click',addFinance);$('#financePrevMonth').addEventListener('click',()=>moveFinanceMonth(-1));$('#financeNextMonth').addEventListener('click',()=>moveFinanceMonth(1));$('#financeThisMonth').addEventListener('click',()=>{state.financeView=new Date();renderFinance()});$('#financeDate').value=DB.today();$('#financeAmount').addEventListener('input',e=>{const d=e.target.value.replace(/[^0-9]/g,'');e.target.value=d?Number(d).toLocaleString('ko-KR'):''});
    $$('#squareTabs [data-square]').forEach(b=>b.addEventListener('click',()=>switchSquare(b.dataset.square)));$('#featureSubmit').addEventListener('click',addFeature);$('#securityReportOpen').addEventListener('click',()=>openModal('securityModal'));$('#securitySubmit').addEventListener('click',submitSecurity);$('#commentSubmit').addEventListener('click',submitComment);$('#publishConfirm').addEventListener('click',publishCurrent);$('#communityTermsCheck').addEventListener('change',e=>$('#communityTermsAccept').disabled=!e.target.checked);$('#communityTermsAccept').addEventListener('click',acceptCommunityTerms);$('#reportSubmit').addEventListener('click',submitReport);
    $$('#settingsMenu [data-settings]').forEach(b=>b.addEventListener('click',()=>switchSettings(b.dataset.settings)));$('#profileSave').addEventListener('click',saveProfile);$('#publicProfileToggle').addEventListener('click',togglePublicProfile);$('#exportData').addEventListener('click',exportData);$('#logoutBtn').addEventListener('click',doLogout);$('#deleteAccountOpen').addEventListener('click',()=>openModal('deleteModal'));$('#deleteConfirmText').addEventListener('input',e=>$('#deleteAccountConfirm').disabled=e.target.value.trim()!=='삭제합니다');$('#deleteAccountConfirm').addEventListener('click',deleteAccount);
    $('#lightboxClose').addEventListener('click',()=>$('#lightbox').classList.remove('show'));$('#lightboxPrev').addEventListener('click',()=>moveLightbox(-1));$('#lightboxNext').addEventListener('click',()=>moveLightbox(1));$('#lightbox').addEventListener('click',e=>{if(e.target.id==='lightbox')e.currentTarget.classList.remove('show')});document.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')moveLightbox(-1);if(e.key==='ArrowRight')moveLightbox(1);if(e.key==='Escape'){$$('.modal-backdrop.show').forEach(m=>closeModal(m.id));$('#lightbox').classList.remove('show')}});
    $('#habitSchedule').insertAdjacentHTML('beforeend','<option value="selected_weekdays">선택 요일</option>');$('#habitSchedule').insertAdjacentHTML('afterend','<fieldset id="habitWeekdayPicker" class="weekday-picker hidden"><legend>요일</legend><label><input type="checkbox" value="1">월</label><label><input type="checkbox" value="2">화</label><label><input type="checkbox" value="3">수</label><label><input type="checkbox" value="4">목</label><label><input type="checkbox" value="5">금</label><label><input type="checkbox" value="6">토</label><label><input type="checkbox" value="0">일</label></fieldset>');$('#habitSchedule').addEventListener('change',()=>$('#habitWeekdayPicker').classList.toggle('hidden',$('#habitSchedule').value!=='selected_weekdays'));
    if(!$('#recordFilter option[value="즐겨찾기"]'))$('#recordFilter').insertAdjacentHTML('beforeend','<option value="즐겨찾기">즐겨찾기</option>');const financePane=$('#module-finance');if(financePane){$('#personalFinanceHost').appendChild(financePane);$('#labTabs [data-module="finance"]').classList.add('hidden')};$('#labSearch').addEventListener('input',()=>{renderProjects();renderIdeas();renderWorks();renderFinance();renderAllLab()});$('#projectProgress')?.closest('.field')?.classList.add('hidden');
    if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>{});
  }

  async function boot(){bind();updateNetwork();if(DB.initError){$('#authMessage').textContent=DB.initError;return}try{const session=await DB.getSession();if(session)await enterApp()}catch(e){console.error(e);$('#authMessage').textContent='초기 연결에 실패했습니다. 네트워크 또는 Supabase 설정을 확인해 주세요.'}}
  function showPendingProjectFiles(){const inp=$('#projectProcessFiles'),host=$('#projectPendingFileList');if(!inp||!host)return;const files=[...(inp.files||[])];host.innerHTML=files.length?`<small class="muted">저장할 파일 ${files.length}개</small>${files.map(f=>`<div class="file-row pending"><span>${esc(f.name)}</span><small>저장 대기</small></div>`).join('')}`:''}
  async function uploadPendingProjectFiles(project=state.projectEdit){const p=project,inp=$('#projectProcessFiles');if(!p||!inp?.files?.length)return;for(const file of [...inp.files]){const meta=await Storage.uploadPrivate(file,'projects');try{await DB.addProjectFile({project_id:p.id,storage_path:meta.path,original_name:file.name,mime_type:meta.type,size_bytes:meta.size})}catch(err){await Storage.removePrivatePaths([meta.path]).catch(()=>{});throw err}}inp.value='';showPendingProjectFiles();toast('과정 파일을 저장했습니다.')}
  document.addEventListener('click',e=>{if(e.target.closest('[data-open-project]')&&!$('#projectProcessFiles')){const save=$('#projectDetailSave');if(save){const label=document.createElement('label');label.className='photo-picker';label.innerHTML='과정 파일 추가 · 파일당 최대 20MB<input id="projectProcessFiles" type="file" multiple accept="image/*,.pdf,.doc,.docx,.ppt,.pptx,.xls,.xlsx,.txt,.hwp,.hwpx">';const pending=document.createElement('div');pending.id='projectPendingFileList';pending.className='file-list pending-file-list';save.parentElement.before(label);label.after(pending);label.querySelector('input').addEventListener('change',showPendingProjectFiles)}} });
  async function showProjectFiles(){const p=state.projectEdit;if(!p)return;const inp=$('#projectProcessFiles');if(!inp)return;let host=$('#projectProcessFileList');if(!host){host=document.createElement('div');host.id='projectProcessFileList';host.className='file-list';inp.closest('label').after(host)}try{const rows=await DB.listProjectFiles(p.id);host.innerHTML=rows.length?rows.map(f=>`<div class="file-row"><span>${esc(f.original_name)}</span><button class="link-btn" data-download-project-file="${esc(f.storage_path)}" data-project-name="${esc(f.original_name)}">열기</button></div>`).join(''):'<small class="muted">저장된 과정 파일이 없습니다.</small>'}catch{host.innerHTML='<small class="muted">과정 파일 목록을 불러오지 못했습니다.</small>'}}
  document.addEventListener('click',e=>{if(e.target.closest('[data-open-project]'))setTimeout(()=>showProjectFiles(),300);const dl=e.target.closest('[data-download-project-file]');if(dl)Storage.downloadPrivate(dl.dataset.downloadProjectFile,dl.dataset.projectName).catch(err=>toast(err.message))});
  boot();
})();
